import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";

export const metadata: Metadata = { title: "Кампус і сервіси", description: "Гуртожиток, бібліотека, навчальні простори та студентські сервіси АПСВТ." };
const places = [
  { n: "01", title: "Гуртожиток", text: "Мебльовані двомісні кімнати на території Академії, кухні на поверхах, пральня та тренажерна зала.", href: "/facilities/dormitory", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1400&q=88&auto=format&fit=crop" },
  { n: "02", title: "Бібліотека", text: "Читальні зали, відкритий доступ до фонду, електронний каталог та навчально-методичні комплекси.", href: "/facilities/library", image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1400&q=88&auto=format&fit=crop" },
  { n: "03", title: "Навчальний кампус", text: "Аудиторії, юридична клініка, спеціалізовані лабораторії, коворкінги та простори для подій.", href: "/facilities/campus", image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1400&q=88&auto=format&fit=crop" },
];
export default function Page() { return <main id="top"><SiteHeader /><section className="phero img"><div className="bgi"><img src="https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=1800&q=92&auto=format&fit=crop" alt="Університетський кампус" /></div><div className="wrap"><div className="crumb">Головна / Кампус</div><h1>Простір для<br />навчання і життя</h1><p className="lead">Усе поруч: навчальні аудиторії, бібліотека, житло, підтримка здоров’я й місця для спільної роботи.</p></div></section><div className="phero-rule" /><section><div className="wrap"><div className="sec-head"><div><div className="idx">01 / Кампус</div><h2>Місця та сервіси</h2></div></div><div className="facility-grid">{places.map((place) => <Link className="facility-card" href={place.href} key={place.title}><div className="ph"><img src={place.image} alt="" /></div><span>{place.n}</span><div><h2>{place.title}</h2><p>{place.text}</p></div><b>→</b></Link>)}</div></div></section><section className="stats"><div className="wrap stat-grid"><div className="stat"><b>3-А</b><span>навчальний корпус</span></div><div className="stat"><b>3-Б</b><span>гуртожиток і бібліотека</span></div><div className="stat"><b>70k<i>+</i></b><span>примірників у фонді</span></div><div className="stat"><b>203</b><span>місця у гуртожитку</span></div></div></section><section><div className="wrap split"><div className="copy"><div className="idx">02 / Доступність</div><h2>Кампус, що підтримує</h2><p className="lead">Навчальні й побутові сервіси зібрані на одній території біля станції метро «Теремки».</p><p>В Академії працюють медичний пункт, два буфети, спортивні простори та служби супроводу. Потреби доступності можна повідомити під час вступної консультації.</p></div><div className="panel"><h3>Швидкі маршрути</h3><ul><li><span className="y">01</span><Link href="/schedule">Розклад занять</Link></li><li><span className="y">02</span><Link href="/academic-calendar">Навчальний рік</Link></li><li><span className="y">03</span><Link href="/contacts">Як дістатися</Link></li></ul></div></div></section><SiteFooter /></main> }
