import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";

export const metadata: Metadata = { title: "Вступ 2026", description: "Зрозумілий маршрут вступу до АПСВТ у 2026 році." };
const steps=[
  ["01","Обери програму","Порівняй зміст, кар’єрні сценарії та формат навчання."],
  ["02","Поговори з нами","Отримай персональну консультацію й перевір перелік документів."],
  ["03","Подай заяву","Створи електронний кабінет вступника та визнач пріоритети."],
  ["04","Стань студентом","Підтвердь вибір, підпиши договір і отримай доступ до цифрового кампусу."],
];
export default function AdmissionsPage(){return <main id="top"><SiteHeader inverse />
  <section className="admission-hero"><div className="admission-copy"><span className="kicker yellow">Вступ 2026</span><h1>Твоя освіта.<br />Твій <i>маршрут.</i></h1><p>Без зайвої бюрократії: зрозумілий план, жива консультація й підтримка від першого питання до студентського квитка.</p><a className="button-light" href="#consultation">Почати з консультації →</a></div><div className="admission-photo"><img src="https://images.unsplash.com/photo-1529390079861-591de354faf5?w=1800&q=92&auto=format&fit=crop" alt="Студенти Академії" /><div className="deadline"><span>Наступна подія</span><b>22 / 08</b><p>День відкритих дверей</p></div></div></section>
  <section className="route section-pad"><div className="section-heading"><div><span className="kicker blue">Чотири кроки</span><h2>Від вибору<br /><i>до зарахування.</i></h2></div></div><div className="route-grid">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="admission-facts section-pad"><div><span className="kicker yellow">Коротко про головне</span><h2>Усе, що потрібно<br />знати <i>заздалегідь.</i></h2></div><div className="facts-list"><details open><summary>Які документи потрібні?</summary><p>Документ про освіту, документ, що посвідчує особу, реєстраційний номер, фото та мотиваційний лист. Точний перелік залежить від категорії вступника.</p></details><details><summary>Чи є бюджетні місця?</summary><p>Умови фінансування залежать від конкурсної пропозиції. Консультант допоможе перевірити актуальні можливості для обраної програми.</p></details><details><summary>Чи можна навчатися дистанційно?</summary><p>Програми поєднують аудиторний і цифровий досвід. Формат та інтенсивність уточнюються для кожної освітньої траєкторії.</p></details><details><summary>Чи є гуртожиток?</summary><p>Так. Місця надаються за заявою; команда вступу пояснить строки та порядок поселення.</p></details></div></section>
  <section className="consultation" id="consultation"><div><span className="kicker yellow">Приймальна комісія</span><h2>Постав запитання.<br />Отримай <i>план дій.</i></h2></div><form action="mailto:pk@socosvita.kiev.ua" method="post" encType="text/plain"><label>Ім’я<input name="name" required placeholder="Як до вас звертатися" /></label><label>Телефон або e-mail<input name="contact" required placeholder="Зручний контакт" /></label><label>Що цікавить?<select name="program"><option>Вибір програми</option><option>Документи для вступу</option><option>Вартість навчання</option><option>Гуртожиток</option><option>Магістратура</option></select></label><label className="full">Ваше запитання<textarea name="question" rows={4} placeholder="Розкажіть, із чим допомогти" /></label><button type="submit">Надіслати запит ↗</button><p>Або телефонуйте: <a href="tel:+380445260664">+38 (044) 526-06-64</a></p></form></section>
  <section className="inline-cta"><h2>Спочатку хочете<br /><i>порівняти програми?</i></h2><Link href="/programs">До каталогу програм ↗</Link></section><SiteFooter /></main>}
