"use client";

import { useMemo, useState } from "react";
import type { Post } from "@/lib/data";
import type { ContentItem } from "@/lib/content";
import type { ContentKind } from "@/lib/content";
import type { EditorialProfile, Publisher } from "@/lib/auth";
import type { PageDocument } from "@/lib/documents";
import { accessScopeLabel, canEditPage, contentKindPagePath } from "@/lib/editorial-access";
import { OperationsEditor } from "./OperationsEditor";
import { AccessManager } from "./AccessManager";
import { DocumentManager } from "./DocumentManager";

type FormState={title:string;excerpt:string;body:string;category:string;imageUrl:string;imageAlt:string;status:"draft"|"published";featured:boolean;publishedAt:string|null;slug?:string};
const empty:FormState={title:"",excerpt:"",body:"",category:"Новини",imageUrl:"",imageAlt:"",status:"draft",featured:false,publishedAt:null};

export function PanelEditor({initialPosts,initialContent,initialDocuments,publisher,initialProfiles}:{initialPosts:Post[];initialContent:ContentItem[];initialDocuments:PageDocument[];publisher:Publisher;initialProfiles:EditorialProfile[]}){
  const [posts,setPosts]=useState(initialPosts);const [form,setForm]=useState<FormState>(empty);const [editing,setEditing]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const published=useMemo(()=>posts.filter(p=>p.status==="published").length,[posts]);
  const canManageNews=canEditPage(publisher,"/news");
  const allowedKinds=(Object.entries(contentKindPagePath).filter(([,path])=>canEditPage(publisher,path)).map(([kind])=>kind)) as ContentKind[];
  const scopeLabel=accessScopeLabel(publisher.accessScopes);
  function change<K extends keyof FormState>(key:K,value:FormState[K]){setForm(current=>({...current,[key]:value}))}
  function edit(post:Post){setEditing(post.id);setForm({title:post.title,excerpt:post.excerpt,body:post.body,category:post.category,imageUrl:post.imageUrl,imageAlt:post.imageAlt,status:post.status,featured:post.featured,publishedAt:post.publishedAt,slug:post.slug});window.scrollTo({top:0,behavior:"smooth"})}
  function reset(){setEditing(null);setForm(empty);setMessage("")}
  async function upload(file:File){setBusy(true);setMessage("Завантажуємо фото…");const data=new FormData();data.append("file",file);const response=await fetch("/api/uploads",{method:"POST",body:data});const result=await response.json() as {url?:string;error?:string};if(!response.ok||!result.url){setMessage(result.error||"Не вдалося завантажити фото");setBusy(false);return}change("imageUrl",result.url);if(!form.imageAlt)change("imageAlt",file.name.replace(/[-_]/g," "));setMessage("Фото готове");setBusy(false)}
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage(editing?"Зберігаємо зміни…":"Створюємо матеріал…");const response=await fetch(editing?`/api/posts/${editing}`:"/api/posts",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const result=await response.json() as Post & {error?:string};if(!response.ok){setMessage(result.error||"Не вдалося зберегти");setBusy(false);return}setPosts(current=>editing?current.map(p=>p.id===editing?result:p):[result,...current]);setMessage(result.status==="published"?"Матеріал опубліковано":"Чернетку збережено");setEditing(null);setForm(empty);setBusy(false)}
  async function remove(id:string){if(!confirm("Видалити цей матеріал?"))return;setBusy(true);const response=await fetch(`/api/posts/${id}`,{method:"DELETE"});if(response.ok){setPosts(current=>current.filter(p=>p.id!==id));setMessage("Матеріал видалено")}else setMessage("Не вдалося видалити");setBusy(false)}
  return <div className="panel-shell">
    <aside className="panel-side"><div className="panel-brand"><span>АП</span><b>Редакційна<br/>панель</b></div><nav>{canManageNews&&<><a className="active" href="#editor">Новий матеріал</a><a href="#materials">Усі публікації</a></>}{allowedKinds.length>0&&<a href="#operations">Керування сайтом</a>}<a href="#documents">Документи сторінок</a><a href="/panel/scheduler">Розумний планувальник</a><a href="/panel/workspace">BytesLab × Академія</a>{publisher.role==="admin"&&<a href="#access">Користувачі</a>}<a href="/" target="_blank">Відкрити сайт ↗</a></nav><div className="panel-user"><span>{publisher.role==="admin"?"Адміністратор":scopeLabel}</span><b>{publisher.displayName}</b><form action="/auth/signout" method="post"><button type="submit">Вийти</button></form></div></aside>
    <main className="panel-main"><header className="panel-top"><div><span>{publisher.role==="admin"?"Повний доступ":`Доступ · ${scopeLabel}`}</span><h1>{canManageNews?(editing?"Редагувати матеріал":"Створити нову історію"):"Редагування сторінки"}</h1></div><div className="panel-stats"><div><b>{initialDocuments.length}</b><span>документів</span></div><div><b>{published}</b><span>публікацій</span></div></div></header>
      {canManageNews&&<><form className="editor" id="editor" onSubmit={submit}><section className="editor-fields"><label>Заголовок<input required value={form.title} onChange={e=>change("title",e.target.value)} placeholder="Сильний і зрозумілий заголовок" /></label><div className="field-row"><label>Категорія<select value={form.category} onChange={e=>change("category",e.target.value)}><option>Новини</option><option>Вступ</option><option>Освіта</option><option>Наука</option><option>Міжнародне</option><option>Студенти</option><option>Події</option></select></label><label>Статус<select value={form.status} onChange={e=>change("status",e.target.value as "draft"|"published")}><option value="draft">Чернетка</option><option value="published">Опублікувати</option></select></label></div><label>Короткий опис<textarea required rows={3} value={form.excerpt} onChange={e=>change("excerpt",e.target.value)} placeholder="1–2 речення для картки матеріалу" /></label><label>Текст статті<textarea required className="body-editor" rows={16} value={form.body} onChange={e=>change("body",e.target.value)} placeholder={"Перший абзац — головна думка.\n\nНовий абзац починайте після порожнього рядка."} /></label><label className="toggle"><input type="checkbox" checked={form.featured} onChange={e=>change("featured",e.target.checked)} /><span>Показувати як головний матеріал</span></label></section>
        <aside className="editor-media"><div className="upload-box">{form.imageUrl?<img src={form.imageUrl} alt="Попередній перегляд"/>:<div><b>Фото матеріалу</b><p>JPG, PNG або WebP · до 8 МБ</p></div>}<label className="upload-button">{busy?"Зачекайте…":"Обрати фото"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></label></div><label>Альтернативний опис<input value={form.imageAlt} onChange={e=>change("imageAlt",e.target.value)} placeholder="Що зображено на фото" /></label><label>Або URL зображення<input type="url" value={form.imageUrl} onChange={e=>change("imageUrl",e.target.value)} placeholder="https://…" /></label><div className="publish-box"><p>{message||"Матеріал можна зберегти як чернетку або одразу опублікувати."}</p><button disabled={busy} type="submit">{busy?"Зберігаємо…":editing?"Зберегти зміни":"Зберегти матеріал"}</button>{editing&&<button className="secondary" type="button" onClick={reset}>Скасувати редагування</button>}</div></aside>
      </form>
      <section className="materials" id="materials"><div className="materials-head"><div><span>Архів редакції</span><h2>Усі матеріали</h2></div><button type="button" onClick={reset}>+ Новий</button></div><div className="material-list">{posts.map(post=><article key={post.id}><div className="material-thumb"><img src={post.imageUrl||"/apsvt-students-real.jpg"} alt=""/></div><div><span>{post.category} · {post.status==="published"?"Опубліковано":"Чернетка"}</span><h3>{post.title}</h3><p>{post.excerpt}</p></div><div className="material-actions"><button onClick={()=>edit(post)}>Редагувати</button>{post.status==="published"&&<a href={`/news/${post.slug}`} target="_blank">Переглянути ↗</a>}<button className="danger" onClick={()=>void remove(post.id)}>Видалити</button></div></article>)}</div></section>
      </>}
      {allowedKinds.length>0&&<OperationsEditor initialContent={initialContent} allowedKinds={allowedKinds}/>}
      <DocumentManager initialDocuments={initialDocuments} publisher={publisher}/>
      {publisher.role==="admin"&&<AccessManager initialProfiles={initialProfiles} currentUserId={publisher.id}/>}
    </main>
  </div>
}
