import Link from "next/link";
import { SiteHeader } from "./components/SiteHeader";
import { SiteFooter } from "./components/SiteFooter";
import { NewsCard } from "./components/NewsCard";
import { getPosts } from "@/lib/data";

const programs=[["01","Право","Бакалавр · Магістр"],["02","Економіка","Бакалавр · Магістр"],["03","Менеджмент","Бакалавр · Магістр"],["04","Маркетинг","Бакалавр · Магістр"],["05","Соціальна робота","Бакалавр · Магістр"],["06","Психологія","Бакалавр · Магістр"],["07","Туризм і гостинність","Бакалавр · Магістр"]];

export default async function Home(){const posts=await getPosts({limit:3});return <main id="top"><SiteHeader/>
  <section className="home-hero"><div className="hero-bg"><img src="/apsvt-hero.png" alt="Студенти Академії у вечірньому світлі"/></div><div className="wrap hero-inner"><div className="hero-eyebrow mono"><span>Вищий навчальний заклад</span><b>Київ, Україна</b><span>З 1993 року</span></div><h1><span>Праця.</span><span>Суспільство.</span><span>Туризм.</span></h1><div className="hero-foot"><p>Освіта, що поєднує професійну майстерність, соціальну відповідальність та міжнародний горизонт.</p><div><Link className="cta" href="/programs"><span>Обрати програму</span></Link><Link className="cta ghost" href="/admissions"><span>Вступ 2026</span></Link></div></div></div><span className="scroll-hint">Гортайте</span></section><div className="hero-rule"/>
  <div className="ticker"><div className="ticker-track"><span>Право</span><span>Економіка</span><span>Менеджмент</span><span>Соціальна робота</span><span>Психологія</span><span>Туризм</span><span>Міжнародні можливості</span><span>Право</span><span>Економіка</span><span>Менеджмент</span><span>Соціальна робота</span><span>Психологія</span></div></div>
  <section><div className="wrap"><div className="sec-head"><div><div className="idx">01 / Програми</div><h2>Освітні траєкторії</h2></div><Link className="sec-link" href="/programs">Усі програми →</Link></div><div className="prow-list">{programs.map(([n,title,level])=><Link className="prow" href="/programs" key={title}><span className="n">{n}</span><h3>{title}</h3><span className="lv">{level}</span><span className="go">→</span></Link>)}</div></div></section>
  <section className="soft"><div className="wrap split"><div className="collage"><div className="ph main"><img src="https://images.unsplash.com/photo-1543269865-cbf427effbad?w=1600&q=90&auto=format&fit=crop" alt="Студенти працюють з викладачем"/></div><div className="ph over"><img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=900&q=90&auto=format&fit=crop" alt="Командна робота студентів"/></div><span className="chip">Люди в центрі</span></div><div className="copy"><div className="idx">02 / Про Академію</div><h2>Знання, що стає дією</h2><p className="lead">Ми поєднуємо академічну глибину з практикою — від юридичної клініки до міжнародних дослідницьких команд.</p><p>Невеликі групи, особиста увага викладачів і свобода формувати власну траєкторію роблять навчання <b>живим, відповідальним і корисним</b>.</p><Link className="cta dark" href="/about"><span>Познайомитися з Академією</span></Link></div></div></section>
  <section className="stats"><div className="wrap stat-grid"><div className="stat"><b>33<i>+</i></b><span>роки досвіду</span></div><div className="stat"><b>7</b><span>освітніх напрямів</span></div><div className="stat"><b>30<i>+</i></b><span>міжнародних партнерів</span></div><div className="stat"><b>1:12</b><span>викладачів до студентів</span></div></div></section>
  <section><div className="wrap"><div className="sec-head"><div><div className="idx">03 / Новини</div><h2>Академія сьогодні</h2></div><Link className="sec-link" href="/news">Усі матеріали →</Link></div><div className="news-grid">{posts.map(post=><NewsCard post={post} key={post.id}/>)}</div></div></section>
  <section className="bigcta"><div className="wrap"><div className="mono">Вступ 2026</div><h2>Ваш наступний<br/>крок починається тут.</h2><p>Порівняйте програми, отримайте консультацію та складіть персональний план вступу.</p><Link className="cta" href="/admissions"><span>Почати вступ</span></Link></div></section><SiteFooter/></main>}
