import Link from "next/link";
import { SiteHeader } from "./components/SiteHeader";
import { SiteFooter } from "./components/SiteFooter";
import { NewsCard } from "./components/NewsCard";
import { getPosts, stakeholderDiscussionNewsSlug } from "@/lib/data";
import { programs } from "@/lib/programs";

export default async function Home(){const posts=await getPosts({limit:8});return <main id="top"><SiteHeader/>
  <section className="home-hero"><div className="hero-bg"><img src="/apsvt-hero.png" alt="Студенти Академії у вечірньому світлі"/></div><div className="wrap hero-inner"><div className="hero-eyebrow mono"><span>Заклад вищої освіти</span><b>Київ, Україна</b><span>З 1993 року</span></div><h1><span>Праця.</span><span>Суспільство.</span><span>Туризм.</span></h1><div className="hero-foot"><p>Освіта, що поєднує професійну майстерність, соціальну відповідальність та міжнародний горизонт.</p><div><Link className="cta" href="/programs"><span>Обрати програму</span></Link><Link className="cta ghost" href="/admissions"><span>Вступ 2026</span></Link></div></div></div><span className="scroll-hint">Гортайте</span></section><div className="hero-rule"/>
  <div className="ticker"><div className="ticker-track"><span>Право</span><span>Фінанси</span><span>Менеджмент</span><span>Маркетинг</span><span>Соціальна робота</span><span>Психологія</span><span>Торгівля</span><span>Публічне управління</span><span>Право</span><span>Фінанси</span><span>Менеджмент</span><span>Міжнародні можливості</span></div></div>
  <section className="home-announcement"><div className="wrap home-announcement-grid"><div className="home-announcement-date"><span>Онлайн</span><b>26</b><small>серпня · 12:00</small></div><div><div className="idx">Оголошення · Юридичний факультет</div><h2>Обговорення освітніх програм D8 і D4</h2><p>До участі запрошуються стейкхолдери програм «Право» та «Публічне управління та адміністрування».</p></div><div className="home-announcement-actions"><a className="cta" href="https://zoom.us/j/3036503681?pwd=QUNhTE14SjVWa3htTy9OZjRjQ2IzQT09" target="_blank" rel="noreferrer"><span>Приєднатися до Zoom ↗</span></a><Link href={`/news/${stakeholderDiscussionNewsSlug}`}>Деталі оголошення →</Link></div></div></section>
  <section><div className="wrap"><div className="sec-head"><div><div className="idx">01 / Програми</div><h2>Освітні траєкторії</h2></div><Link className="sec-link" href="/programs">Усі програми →</Link></div><div className="prow-list">{programs.map(program=><Link className="prow" href={`/programs/${program.slug}`} key={program.slug}><span className="n">{program.number}</span><h3>{program.title}</h3><span className="lv">{program.levels}</span><span className="go">→</span></Link>)}</div></div></section>
  <section className="soft"><div className="wrap split"><div className="collage"><div className="ph main"><img src="/apsvt-students-real.jpg" alt="Випускники та викладачі Академії"/></div><div className="ph over"><img src="/apsvt-event-real.jpg" alt="Учасники події в Академії"/></div><span className="chip">Люди в центрі</span></div><div className="copy"><div className="idx">02 / Про Академію</div><h2>Знання, що стає дією</h2><p className="lead">Ми поєднуємо академічну глибину з практикою — від юридичної клініки до міжнародних дослідницьких команд.</p><p>Невеликі групи, особиста увага викладачів і свобода формувати власну траєкторію роблять навчання <b>живим, відповідальним і корисним</b>.</p><Link className="cta dark" href="/about"><span>Познайомитися з Академією</span></Link></div></div></section>
  <section className="stats"><div className="wrap stat-grid"><div className="stat"><b>33<i>+</i></b><span>роки досвіду</span></div><div className="stat"><b>9</b><span>освітніх напрямів</span></div><div className="stat"><b>30<i>+</i></b><span>міжнародних партнерів</span></div><div className="stat"><b>1:12</b><span>викладачів до студентів</span></div></div></section>
  <section className="home-important"><div className="wrap"><div className="home-important-head"><div><div className="idx">03 / Важливі матеріали</div><h2>Документи й ресурси Академії</h2></div><p>Ключові файли зібрані там, де вони потрібні студентам, вступникам, викладачам і дослідникам.</p></div><div className="home-important-grid">
    <Link href="/students/guide"><span>Студенту</span><h3>Путівник студента</h3><p>Електронний кабінет, розклад, оцінювання та сервіси Академії.</p><b>Переглянути →</b></Link>
    <a href="/documents/academy/statute-2017.pdf" target="_blank" rel="noreferrer"><span>Про Академію</span><h3>Статут АПСВТ</h3><p>Установчий документ Академії у редакції 2017 року.</p><b>PDF ↗</b></a>
    <Link href="/programs#doctoral-programmes"><span>Аспірантура</span><h3>Програми PhD</h3><p>A5, C1, C4 і D4: офіційні освітньо-наукові програми 2025 року.</p><b>Переглянути →</b></Link>
    <Link href="/international#greenfinedu"><span>Erasmus+</span><h3>GreenFinEDU</h3><p>Курси, презентації та колекції матеріалів про сталі фінанси.</p><b>Відкрити →</b></Link>
    <Link href="/events/graduation-2026"><span>Спільнота</span><h3>Свято вручення дипломів</h3><p>Фотогалерея випускного свята та повна колекція матеріалів 2026 року.</p><b>Дивитися галерею →</b></Link>
  </div></div></section>
  <section className="home-hiring"><div className="wrap home-hiring-grid"><div><div className="idx">04 / Команда Академії</div><h2>Шукаємо<br/>викладачів</h2></div><div className="home-hiring-copy"><span>Новий конкурс №2 і №3</span><p>Відкрито 18 посад на кафедрі української та іноземних мов і гуманітарних наук та факультеті психології і соціального розвитку. Заяви приймаються до 16 вересня 2026 року включно.</p><Link className="cta dark" href="/vacancies#competition-2-3"><span>Переглянути вакансії</span></Link></div></div></section>
  <section className="home-access"><div className="wrap"><div className="sec-head"><div><div className="idx">05 / Швидкий доступ</div><h2>Потрібне — одразу</h2></div></div><div className="access-grid"><Link href="/schedule"><span>01</span><h3>Розклад</h3><b>→</b></Link><Link href="/academic-calendar"><span>02</span><h3>Навчальний рік</h3><b>→</b></Link><Link href="/facilities"><span>03</span><h3>Кампус і житло</h3><b>→</b></Link><Link href="/research/journals"><span>04</span><h3>Наукові видання</h3><b>→</b></Link></div></div></section>
  <section><div className="wrap"><div className="sec-head"><div><div className="idx">06 / Новини</div><h2>Академія сьогодні</h2></div><Link className="sec-link" href="/news">Усі матеріали →</Link></div><div className="news-grid">{posts.map(post=><NewsCard post={post} key={post.id}/>)}</div></div></section>
  <section className="bigcta"><div className="wrap"><div className="mono">Вступ 2026</div><h2>Ваш наступний<br/>крок починається тут.</h2><p>Порівняйте програми, отримайте консультацію та складіть персональний план вступу.</p><Link className="cta" href="/admissions"><span>Почати вступ</span></Link></div></section><SiteFooter/></main>}
