import { officialProgrammeFileBase } from "@/lib/programme-documents";

export const documentCategories = [
  {
    id: "admissions",
    number: "01",
    title: "Вступ і приймальна комісія",
    description: "Правила прийому 2026, положення, вступні випробування, апеляції та окремі процедури.",
  },
  {
    id: "education",
    number: "02",
    title: "Освітні програми та освітній процес",
    description: "Чинні освітньо-професійні програми бакалаврату й магістратури, організація навчання та індивідуальна траєкторія.",
  },
  {
    id: "inclusiveness",
    number: "03",
    title: "Інклюзивність і безбар’єрність",
    description: "Доступність навчального середовища, підтримка вступників і здобувачів з особливими освітніми потребами.",
  },
  {
    id: "quality",
    number: "04",
    title: "Якість освіти",
    description: "Внутрішня система якості, гаранти програм, професійний розвиток викладачів і процедури оновлення програм.",
  },
  {
    id: "integrity",
    number: "05",
    title: "Доброчесність і безпека",
    description: "Етика, перевірка на плагіат, запобігання булінгу, мобінгу, кібербулінгу та харасменту.",
  },
  {
    id: "anticorruption",
    number: "06",
    title: "Запобігання корупції",
    description: "Чинний план заходів, порядок внутрішнього розслідування та канали конфіденційного повідомлення.",
  },
  {
    id: "accreditation",
    number: "07",
    title: "Ліцензії та акредитація",
    description: "Право Академії провадити освітню діяльність і архів сертифікатів освітніх програм.",
  },
  {
    id: "payment",
    number: "08",
    title: "Вартість, оплата й договори",
    description: "Офіційна вартість навчання 2026/27 та шаблони договорів про освітні послуги.",
  },
  {
    id: "governance",
    number: "09",
    title: "Структура та установчі документи",
    description: "Організаційна структура, штатний розпис, Статут Академії та ключові положення про внутрішню організацію.",
  },
  {
    id: "doctoral",
    number: "10",
    title: "Аспірантура та освітньо-наукові програми",
    description: "Програми підготовки докторів філософії та відомості про забезпечення освітньої діяльності.",
  },
  {
    id: "international-projects",
    number: "11",
    title: "Міжнародні освітні проєкти",
    description: "Програми курсів, презентації та офіційні матеріали Erasmus+ і модуля Жан Моне GreenFinEDU.",
  },
  {
    id: "research",
    number: "12",
    title: "Методичні та наукові матеріали",
    description: "Збірники конференцій, звіти про наукову роботу та методичні матеріали для навчання й досліджень.",
  },
] as const;

export type DocumentCategoryId = typeof documentCategories[number]["id"];

export type OfficialDocument = {
  id: string;
  category: DocumentCategoryId;
  title: string;
  description: string;
  href: string;
  format: "PDF" | "DOCX" | "PPTX" | "WEB";
  pages?: number;
  updated?: string;
  status?: "current" | "reference";
  indexFile?: string;
  admissionFile?: string;
};

const admissionDocuments: OfficialDocument[] = [
  ["rules-2026", "Правила прийому на навчання до АПСВТ у 2026 році", "Основний документ про умови, строки, конкурс і зарахування.", "01-pravyla-pryiomu-apsvt-2026.pdf", 73],
  ["admission-commission", "Положення про Приймальну комісію", "Повноваження, склад і порядок роботи Приймальної комісії.", "02-polozhennia-pro-pryimalnu-komisiiu.pdf", 16],
  ["entrance-boards", "Положення про комісії для вступних випробувань", "Організація предметних, фахових та атестаційних комісій.", "03-polozhennia-pro-komisii-vstupnykh-vyprobuvan.pdf", 7],
  ["threat-procedure", "Дії Приймальної комісії в умовах загроз", "Порядок роботи під час повітряної тривоги та інших небезпек.", "04-poriadok-dii-pk-v-umovakh-zahroz.pdf", 5],
  ["inclusive-admissions", "Забезпечення інклюзивності вступної кампанії", "Умови доступності та підтримки вступників з особливими освітніми потребами.", "05-poriadok-inkliuzyvnosti-vstupnoi-kampanii.pdf", 6],
  ["applicant-work-storage", "Зберігання робіт вступників", "Строки, відповідальні особи та правила доступу до екзаменаційних робіт.", "06-poriadok-zberihannia-robit-vstupnykiv.pdf", 5],
  ["foreign-admissions", "Організація прийому іноземців до АПСВТ", "Процедура вступу іноземних громадян та осіб без громадянства.", "07-poriadok-pryiomu-inozemtsiv.pdf", 6],
  ["entrance-exams", "Проведення вступних випробувань", "Підготовка, проведення, оцінювання й оформлення результатів.", "08-poriadok-provedennia-vstupnykh-vyprobuvan.pdf", 15],
  ["media-accreditation", "Акредитація представників медіа", "Порядок присутності представників медіа під час вступної кампанії.", "09-poriadok-akredytatsii-media.pdf", 4],
  ["appeals", "Подання і розгляд апеляцій", "Як, коли та кому подати апеляцію щодо результату вступного випробування.", "10-poriadok-podannia-apeliatsii.pdf", 6],
  ["remote-exams", "Додаток 8 — дистанційні вступні випробування", "Технічні та організаційні правила дистанційного формату.", "11-dodatok-8.pdf", 7],
].map(([id, title, description, file, pages]) => ({
  id: String(id),
  category: "admissions",
  title: String(title),
  description: String(description),
  href: `/documents/admissions/${file}`,
  format: "PDF",
  pages: Number(pages),
  updated: "2026",
  status: "current",
  admissionFile: String(file),
}));

export const officialDocuments: OfficialDocument[] = [
  ...admissionDocuments,
  {
    id: "entrance-schedule-bachelor-2026",
    category: "admissions",
    title: "Розклад співбесід — бакалаврат, 2026",
    description: "Дати, час, аудиторія та дистанційний формат співбесід для вступників на бакалаврат.",
    href: "/documents/admissions/entrance-exams/bakalavrat-spivbesidy-2026.pdf",
    format: "PDF",
    pages: 1,
    updated: "2026",
    status: "current",
  },
  {
    id: "entrance-schedule-master-2026",
    category: "admissions",
    title: "Розклад співбесід і фахових іспитів — магістратура, 2026",
    description: "Консультації, співбесіди з іноземної мови та фахові іспити для вступників на магістратуру.",
    href: "/documents/admissions/entrance-exams/mahistratura-spivbesidy-fakhovi-ispity-2026.pdf",
    format: "PDF",
    pages: 4,
    updated: "2026",
    status: "current",
  },
  {
    id: "entrance-schedule-phd-2026",
    category: "admissions",
    title: "Розклад вступних випробувань — аспірантура, 2026",
    description: "Іноземна мова, методологія досліджень, іспити зі спеціальності та презентація дослідницької пропозиції.",
    href: "/documents/admissions/entrance-exams/aspirantura-vstupni-vyprobuvannia-2026.pdf",
    format: "PDF",
    pages: 2,
    updated: "2026",
    status: "current",
  },
  {
    id: "programme-management-bachelor-2025",
    category: "education",
    title: "ОПП D3 «Менеджмент» — бакалавр",
    description: "Офіційна освітньо-професійна програма першого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d3-management-bachelor.pdf`, format: "PDF", pages: 22, updated: "2025", status: "current",
  },
  {
    id: "programme-management-master-2025",
    category: "education",
    title: "ОПП D3 «Менеджмент» — магістр",
    description: "Офіційна освітньо-професійна програма другого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d3-management-master.pdf`, format: "PDF", pages: 13, updated: "2025", status: "current",
  },
  {
    id: "programme-marketing-bachelor-2025", category: "education", title: "ОПП D5 «Маркетинг» — бакалавр",
    description: "Офіційна освітньо-професійна програма першого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d5-marketing-bachelor.pdf`, format: "PDF", pages: 20, updated: "2025", status: "current",
  },
  {
    id: "programme-marketing-master-2025", category: "education", title: "ОПП D5 «Маркетинг» — магістр",
    description: "Офіційна освітньо-професійна програма другого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d5-marketing-master.pdf`, format: "PDF", pages: 15, updated: "2025", status: "current",
  },
  {
    id: "programme-law-bachelor-2025", category: "education", title: "ОПП D8 «Право» — бакалавр",
    description: "Офіційна освітньо-професійна програма першого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d8-law-bachelor.pdf`, format: "PDF", pages: 22, updated: "2025", status: "current",
  },
  {
    id: "programme-law-master-2025", category: "education", title: "ОПП D8 «Право» — магістр",
    description: "Офіційна освітньо-професійна програма другого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d8-law-master.pdf`, format: "PDF", pages: 20, updated: "2025", status: "current",
  },
  {
    id: "programme-psychology-bachelor-2024-2025", category: "education", title: "ОПП C4 «Психологія» — бакалавр",
    description: "Офіційна освітньо-професійна програма першого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/c4-psychology-bachelor-2024-2025.pdf`, format: "PDF", pages: 18, updated: "2024/25", status: "current",
  },
  {
    id: "programme-psychology-business-master-2024-2025", category: "education", title: "ОПП «Психологія бізнесу та управління» — магістр",
    description: "Офіційна магістерська програма з психології бізнесу та управління.",
    href: `${officialProgrammeFileBase}/c4-psychology-business-management-master-2024-2025.pdf`, format: "PDF", pages: 15, updated: "2024/25", status: "current",
  },
  {
    id: "programme-professional-education-bachelor-2025", category: "education", title: "ОПП A5 «Професійна освіта · Цифрові технології» — бакалавр",
    description: "Офіційна програма з професійної педагогіки та цифрових освітніх технологій.",
    href: `${officialProgrammeFileBase}/a5-professional-education-digital-technologies-bachelor.pdf`, format: "PDF", pages: 34, updated: "2025", status: "current",
  },
  {
    id: "programme-professional-education-master-2025", category: "education", title: "ОПП A5 «Професійна освіта · Цифрові технології» — магістр",
    description: "Офіційна магістерська програма з цифрових технологій професійної освіти.",
    href: `${officialProgrammeFileBase}/a5-professional-education-digital-technologies-master.pdf`, format: "PDF", pages: 20, updated: "2025", status: "current",
  },
  {
    id: "programme-public-administration-master-2025", category: "education", title: "ОПП D4 «Публічне управління та адміністрування» — магістр",
    description: "Офіційна освітньо-професійна програма другого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d4-public-administration-master.pdf`, format: "PDF", pages: 18, updated: "2025", status: "current",
  },
  {
    id: "programme-finance-master-2025", category: "education", title: "ОПП D2 «Фінанси, банківська справа, страхування та фондовий ринок» — магістр",
    description: "Офіційна освітньо-професійна програма другого рівня вищої освіти.",
    href: `${officialProgrammeFileBase}/d2-finance-master.pdf`, format: "PDF", pages: 17, updated: "2025", status: "current",
  },
  {
    id: "education-process",
    category: "education",
    title: "Положення про організацію освітнього процесу",
    description: "Основний нормативний документ Академії: програми, оцінювання, мобільність, права здобувачів і процедури навчання.",
    href: "https://www.socosvita.kiev.ua/sites/default/files/%20%D0%BF%D1%80%D0%BE%20%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D1%96%D0%B7%D0%B0%D1%86%D1%96%D1%8E%20%D0%BE%D1%81%D0%B2%D1%96%D1%82%D0%BD%D1%8C%D0%BE%D0%B3%D0%BE%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%83%20%D0%B2%20%D0%90%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D1%96%D1%97_0.pdf",
    format: "PDF",
    pages: 156,
    updated: "2025",
    status: "current",
    indexFile: "0-f43a0e632.txt",
  },
  {
    id: "individual-plan",
    category: "education",
    title: "Положення про індивідуальний навчальний план здобувача",
    description: "Формування та виконання персональної освітньої траєкторії.",
    href: "/documents/archive/old-site/individual-study-plan-2024.pdf",
    format: "PDF",
    pages: 7,
    updated: "2023",
    status: "reference",
    indexFile: "0-07d5ab111.txt",
  },
  {
    id: "academic-status",
    category: "education",
    title: "Відрахування, переривання, поновлення та переведення",
    description: "Порядок зміни академічного статусу та надання академічної відпустки.",
    href: "/documents/archive/old-site/academic-status-2025.pdf",
    format: "PDF",
    pages: 13,
    updated: "2024",
    status: "current",
    indexFile: "document-370a6429f.txt",
  },
  {
    id: "student-government",
    category: "education",
    title: "Положення про студентське самоврядування",
    description: "Органи, вибори, представництво та повноваження студентської спільноти.",
    href: "https://www.socosvita.kiev.ua/educational",
    format: "WEB",
    pages: 8,
    updated: "2024",
    status: "current",
    indexFile: "2024-8220e6384.txt",
  },
  {
    id: "social-scholarship",
    category: "inclusiveness",
    title: "Положення про персональну соціальну стипендію",
    description: "Умови призначення персональної соціальної стипендії Фонду мерії Барселони.",
    href: "/documents/archive/old-site/social-scholarship-2025.pdf",
    format: "PDF",
    pages: 5,
    updated: "2025",
    status: "current",
    indexFile: "document-0ae211046.txt",
  },
  {
    id: "internal-quality-system",
    category: "quality",
    title: "Система внутрішнього забезпечення якості вищої освіти",
    description: "Положення про внутрішні процедури забезпечення та вдосконалення якості освіти в Академії.",
    href: "/documents/archive/old-site/internal-quality-system.pdf",
    format: "PDF",
    pages: 22,
    updated: "2023",
    status: "reference",
  },
  {
    id: "academic-staff-development",
    category: "quality",
    title: "Підвищення кваліфікації педагогічних і науково-педагогічних працівників",
    description: "Положення про професійний розвиток і визнання результатів підвищення кваліфікації працівників Академії.",
    href: "/documents/archive/old-site/academic-staff-development-2025.pdf",
    format: "PDF",
    pages: 9,
    updated: "2025",
    status: "current",
  },
  {
    id: "programme-guarantor",
    category: "quality",
    title: "Положення про гаранта освітньої програми",
    description: "Повноваження, відповідальність і порядок призначення гаранта освітньої програми.",
    href: "/documents/archive/old-site/programme-guarantor.pdf",
    format: "PDF",
    pages: 10,
    updated: "2025",
    status: "current",
  },
  {
    id: "professional-qualifications",
    category: "quality",
    title: "Здобуття та присвоєння професійних кваліфікацій",
    description: "Положення про порядок здобуття і присвоєння професійних кваліфікацій в Академії.",
    href: "/documents/archive/old-site/professional-qualifications-regulation.pdf",
    format: "PDF",
    pages: 9,
    updated: "2025",
    status: "current",
  },
  {
    id: "pedagogical-practice-guidelines",
    category: "education",
    title: "Методичні рекомендації до педагогічної практики",
    description: "Рекомендації для здобувачів другого рівня спеціальності 015 «Професійна освіта».",
    href: "/documents/archive/old-site/pedagogical-practice-guidelines.pdf",
    format: "PDF",
    pages: 37,
    updated: "архів",
    status: "reference",
  },
  {
    id: "educational-programme-approval-stages",
    category: "quality",
    title: "Етапи затвердження нової редакції освітньої програми",
    description: "Графік обговорення, перегляду та затвердження програми «Професійна освіта (Цифрові технології)».",
    href: "/documents/archive/old-site/educational-programme-approval-stages.pdf",
    format: "PDF",
    pages: 2,
    updated: "архів",
    status: "reference",
  },
  {
    id: "reduced-mobility-support",
    category: "inclusiveness",
    title: "Висновок щодо доступності для маломобільних груп населення",
    description: "Оцінка доступності навчального корпусу Академії для осіб з інвалідністю та інших маломобільних груп.",
    href: "/documents/archive/old-site/reduced-mobility-support.pdf",
    format: "PDF",
    pages: 1,
    updated: "архів",
    status: "reference",
  },
  {
    id: "ethics-code",
    category: "integrity",
    title: "Кодекс етики АПСВТ",
    description: "Принципи академічної культури, взаємної поваги та відповідальної поведінки.",
    href: "/documents/archive/old-site/ethics-code.pdf",
    format: "PDF",
    pages: 14,
    updated: "2016",
    status: "current",
    indexFile: "kodeksetyky-3760a4ae3.txt",
  },
  {
    id: "plagiarism-check",
    category: "integrity",
    title: "Порядок перевірки академічних текстів на плагіат",
    description: "Процедура перевірки, показники текстових збігів і відповідальність учасників.",
    href: "/documents/archive/old-site/plagiarism-check-2025.pdf",
    format: "PDF",
    pages: 6,
    updated: "2025",
    status: "current",
    indexFile: "document-df7b61ca7.txt",
  },
  {
    id: "anti-bullying",
    category: "integrity",
    title: "Булінг, мобінг, кібербулінг і харасмент: запобігання та реагування",
    description: "Ознаки порушень, безпечне звернення та алгоритм реагування Академії.",
    href: "/documents/archive/old-site/anti-bullying-harassment-2023.pdf",
    format: "PDF",
    pages: 19,
    updated: "2023",
    status: "current",
    indexFile: "document-28eb75696.txt",
  },
  {
    id: "anti-bullying-measures",
    category: "integrity",
    title: "План заходів із запобігання булінгу, мобінгу, кібербулінгу та харасменту",
    description: "Перелік інформаційних, профілактичних і навчальних заходів Академії на 2024/25 навчальний рік.",
    href: "/documents/archive/old-site/anti-bullying-measures-2025.pdf",
    format: "PDF",
    pages: 1,
    updated: "2024/25",
    status: "reference",
  },
  {
    id: "anticorruption-plan",
    category: "anticorruption",
    title: "План запобігання, виявлення та протидії корупції",
    description: "Чинний план заходів Академії на період 01.01.2024–01.01.2027.",
    href: "https://www.socosvita.kiev.ua/Protydiia_koruptsii",
    format: "WEB",
    updated: "2024–2027",
    status: "current",
  },
  {
    id: "internal-investigation",
    category: "anticorruption",
    title: "Порядок проведення внутрішнього службового розслідування",
    description: "Підстави, комісія, строки та оформлення результатів службового розслідування.",
    href: "/documents/archive/old-site/internal-investigation-2021.pdf",
    format: "PDF",
    pages: 10,
    updated: "2021",
    status: "current",
    indexFile: "poriadok-rozsliduvannia-2021-2c339f741.txt",
  },
  {
    id: "anticorruption-report",
    category: "anticorruption",
    title: "Звіт уповноваженого з питань протидії корупції",
    description: "Оприлюднений звіт про роботу уповноваженої особи Академії.",
    href: "/documents/archive/old-site/anticorruption-report-2023.pdf",
    format: "PDF",
    pages: 1,
    updated: "2023",
    status: "reference",
    indexFile: "20231031-205611-05514622c.txt",
  },
  {
    id: "educational-license",
    category: "accreditation",
    title: "Ліцензія на провадження освітньої діяльності",
    description: "Офіційні відомості про право Академії здійснювати освітню діяльність.",
    href: "/documents/licenses/license-educational-activity-2021.pdf",
    format: "PDF",
    pages: 2,
    updated: "2021",
    status: "current",
    indexFile: "license2021-b31685c41.txt",
  },
  {
    id: "accreditation-archive",
    category: "accreditation",
    title: "Архів сертифікатів освітніх програм",
    description: "16 сканів акредитаційних сертифікатів із переходом до державних реєстрів.",
    href: "/about/licenses#certificates",
    format: "WEB",
    updated: "архів",
    status: "reference",
  },
  {
    id: "tuition-rates",
    category: "payment",
    title: "Вартість навчання у 2026/27 навчальному році",
    description: "Офіційні тарифи для вступників і студентів за програмами та формами навчання.",
    href: "/documents/tuition/tuition-2026-2027.pdf",
    format: "PDF",
    pages: 4,
    updated: "2026/27",
    status: "current",
  },
  {
    id: "education-contract",
    category: "payment",
    title: "Договір про надання платної освітньої послуги",
    description: "Офіційний шаблон договору про платну освітню послугу.",
    href: "/documents/tuition/contract-paid-educational-service.docx",
    format: "DOCX",
    updated: "2025",
    status: "current",
  },
  {
    id: "study-contract",
    category: "payment",
    title: "Договір про навчання",
    description: "Офіційний шаблон договору про навчання в Академії.",
    href: "/documents/tuition/contract-education.docx",
    format: "DOCX",
    updated: "2025",
    status: "current",
  },
  {
    id: "academy-statute-2017",
    category: "governance",
    title: "Статут Академії праці, соціальних відносин і туризму",
    description: "Нова редакція установчого документа, затверджена постановою Президії ФПУ у 2017 році.",
    href: "/documents/academy/statute-2017.pdf",
    format: "PDF",
    pages: 30,
    updated: "2017",
    status: "current",
  },
  {
    id: "academy-organizational-structure-2026",
    category: "governance",
    title: "Організаційна структура Академії",
    description: "Затверджена схема підпорядкування керівництва, факультетів, кафедр, відділів, центрів і служб Академії.",
    href: "/documents/academy/organizational-structure-2026.pdf",
    format: "PDF",
    pages: 2,
    updated: "2026",
    status: "current",
  },
  {
    id: "academy-staffing-schedule-2025",
    category: "governance",
    title: "Витяг зі штатного розпису Академії",
    description: "Структурні підрозділи, посади та кількість штатних одиниць станом на 1 вересня 2025 року.",
    href: "/documents/academy/staffing-schedule-2025.pdf",
    format: "PDF",
    pages: 5,
    updated: "2025",
    status: "current",
  },
  {
    id: "academy-statute-amendments-2022",
    category: "governance",
    title: "Зміни до Статуту Академії",
    description: "Архівний примірник змін до установчого документа Академії, оприлюднений у 2022 році.",
    href: "/documents/archive/old-site/statute-amendments-2022.pdf",
    format: "PDF",
    pages: 2,
    updated: "2022",
    status: "reference",
  },
  {
    id: "individual-study-plan-2019-archive",
    category: "governance",
    title: "Положення про індивідуальний навчальний план студента",
    description: "Архівна редакція положення, затверджена Вченою радою Академії у 2019 році.",
    href: "/documents/regulations/individual-study-plan",
    format: "WEB",
    pages: 9,
    updated: "2019",
    status: "reference",
  },
  {
    id: "best-teacher-competition",
    category: "governance",
    title: "Положення про конкурс «Викладач року Академії»",
    description: "Порядок організації та проведення внутрішнього конкурсу професійної майстерності викладачів.",
    href: "/documents/regulations/teacher-of-year",
    format: "WEB",
    pages: 10,
    updated: "2018",
    status: "reference",
  },
  {
    id: "first-year-guide-2024",
    category: "education",
    title: "Путівник студента Академії",
    description: "Практична пам’ятка про студентський квиток, електронний кабінет, розклад, оцінювання та сервіси кампусу.",
    href: "/students/guide",
    format: "WEB",
    pages: 28,
    updated: "2024",
    status: "reference",
  },
  {
    id: "phd-a5-programme-2025",
    category: "doctoral",
    title: "A5 Професійна освіта (за спеціалізаціями)",
    description: "Освітньо-наукова програма третього рівня вищої освіти.",
    href: "/documents/programmes/phd/2025/a5-professional-education.pdf",
    format: "PDF",
    pages: 26,
    updated: "2025",
    status: "current",
  },
  {
    id: "phd-c1-programme-2025",
    category: "doctoral",
    title: "C1 Економіка та міжнародні економічні відносини",
    description: "Освітньо-наукова програма «Економіка» для підготовки докторів філософії.",
    href: "/documents/programmes/phd/2025/c1-economics.pdf",
    format: "PDF",
    pages: 17,
    updated: "2025",
    status: "current",
  },
  {
    id: "phd-c4-programme-2025",
    category: "doctoral",
    title: "C4 Психологія",
    description: "Освітньо-наукова програма третього рівня вищої освіти.",
    href: "/documents/programmes/phd/2025/c4-psychology.pdf",
    format: "PDF",
    pages: 19,
    updated: "2025",
    status: "current",
  },
  {
    id: "phd-d4-programme-2025",
    category: "doctoral",
    title: "D4 Публічне управління та адміністрування",
    description: "Освітньо-наукова програма третього рівня вищої освіти.",
    href: "/documents/programmes/phd/2025/d4-public-administration.pdf",
    format: "PDF",
    pages: 17,
    updated: "2025",
    status: "current",
  },
  {
    id: "phd-educational-facilities-2025",
    category: "doctoral",
    title: "Відомості про засоби провадження освітньої діяльності",
    description: "Забезпечення освітньо-наукових програм A5, C1, C4 і D4.",
    href: "/documents/programmes/phd/2025/educational-facilities.pdf",
    format: "PDF",
    pages: 21,
    updated: "2025",
    status: "current",
  },
  {
    id: "conference-proceedings-2025",
    category: "research",
    title: "Збірник міжнародної науково-практичної конференції 2025",
    description: "Матеріали конференції про економічні, фінансові, управлінські, маркетингові та правові моделі розвитку України.",
    href: "/documents/archive/old-site/conference-proceedings-2025.pdf",
    format: "PDF",
    pages: 377,
    updated: "2025",
    status: "reference",
  },
  {
    id: "research-report-2017-2018",
    category: "research",
    title: "Звіт з наукової роботи Академії за 2017/18 навчальний рік",
    description: "Архівний огляд напрямів досліджень, публікацій і наукових заходів Академії.",
    href: "/documents/archive/old-site/research-report-2017-2018.pdf",
    format: "PDF",
    pages: 12,
    updated: "2017/18",
    status: "reference",
  },
  {
    id: "legal-clinic-regulation",
    category: "education",
    title: "Положення про юридичну клініку Академії",
    description: "Організація навчально-практичної роботи юридичної клініки та надання правової допомоги.",
    href: "/documents/archive/old-site/legal-clinic-regulation.pdf",
    format: "PDF",
    pages: 4,
    updated: "архів",
    status: "reference",
  },
  {
    id: "forensic-lab-regulation",
    category: "education",
    title: "Положення про навчальну лабораторію криміналістики",
    description: "Завдання, структура та організація роботи навчальної лабораторії юридичного факультету.",
    href: "/documents/archive/old-site/forensic-lab-regulation.pdf",
    format: "PDF",
    pages: 5,
    updated: "архів",
    status: "reference",
  },
  {
    id: "greenfinedu-presentation",
    category: "international-projects",
    title: "Презентація проєкту GreenFinEDU",
    description: "Модуль Жан Моне Erasmus+ № 101126681: мета, команда та план реалізації у 2023–2026 роках.",
    href: "/documents/international/greenfinedu/project-presentation.pptx",
    format: "PPTX",
    updated: "2023–2026",
    status: "current",
  },
  {
    id: "greenfinedu-launch-agenda",
    category: "international-projects",
    title: "Програма презентації GreenFinEDU",
    description: "Двомовна програма офіційної презентації модуля Жан Моне.",
    href: "/documents/international/greenfinedu/project-launch-agenda.docx",
    format: "DOCX",
    updated: "2023",
    status: "reference",
  },
  {
    id: "greenfinedu-intensive-course",
    category: "international-projects",
    title: "GreenFinEDU: програма базового інтенсивного курсу",
    description: "Курс про Європейську зелену угоду та сталі фінанси для студентів заочної форми.",
    href: "/documents/international/greenfinedu/intensive-course-programme.docx",
    format: "DOCX",
    updated: "2023–2026",
    status: "current",
  },
  {
    id: "greenfinedu-advanced-course",
    category: "international-projects",
    title: "GreenFinEDU: програма поглибленого онлайн-курсу",
    description: "Поглиблена програма зі сталої фінансової політики ЄС для бакалаврів і магістрів.",
    href: "/documents/international/greenfinedu/advanced-online-course-programme.docx",
    format: "DOCX",
    updated: "2023–2026",
    status: "current",
  },
  {
    id: "greenfinedu-summer-school",
    category: "international-projects",
    title: "GreenFinEDU: програма літньої школи",
    description: "Навчальна програма для викладачів, публічних службовців, професійних груп і громадськості.",
    href: "/documents/international/greenfinedu/summer-school-programme.docx",
    format: "DOCX",
    updated: "2023–2026",
    status: "current",
  },
];

export const documentStats = {
  documents: officialDocuments.length,
  categories: documentCategories.length,
  searchableDocuments: officialDocuments.filter((document) => document.indexFile || document.admissionFile).length,
};
