import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/app/components/SiteHeader";
import { EnglishFooter } from "@/app/components/EnglishFooter";

export const metadata: Metadata = {
  title: "Tuition and payment",
  description: "Official APSVT tuition rates for 2026/27, bank details, payment safety and education contract templates.",
};

export default function Page() {
  return <main id="top" className="english-page"><SiteHeader />
    <section className="tuition-hero"><div className="wrap tuition-hero-grid"><div><div className="crumb">Home / Tuition and payment</div><span className="tuition-kicker">Official rates · 2026/27</span><h1>Tuition<br />fees<br /><em>2026 / 27</em></h1><p className="lead">Annual, semester and monthly rates, verified bank details and Academy contract templates in one place.</p></div><aside><span className="mono">For 2026 applicants</span><b>from 30,900 <i>UAH / year</i></b><p>Part-time bachelor’s tuition for most programmes.</p><div className="tuition-hero-links"><a href="#english-rates">View rates ↓</a><a href="#english-payment">Go to payment →</a></div></aside></div></section>
    <section id="english-rates"><div className="wrap"><div className="tuition-section-head"><div><div className="idx">01 / New applicants</div><h2>2026/27<br />annual rates</h2></div><p>The official four-page Academy document contains rates by programme, study form, course and payment period.</p></div><div className="tuition-rate-grid">
      <article className="tuition-rate-card"><span>01</span><h3>Most bachelor’s programmes</h3><p>Law, public administration, social work, finance, management, marketing, trade, psychology and professional education / digital technologies.</p><div className="tuition-rate-columns"><div><small>Full-time</small><b>38,600 UAH</b><dl><div><dt>Semester</dt><dd>19,300 UAH</dd></div><div><dt>Month</dt><dd>3,860 UAH</dd></div></dl></div><div><small>Part-time</small><b>30,900 UAH</b><dl><div><dt>Semester</dt><dd>15,450 UAH</dd></div><div><dt>Month</dt><dd>3,090 UAH</dd></div></dl></div></div></article>
      <article className="tuition-rate-card"><span>02</span><h3>Tourism and Recreation</h3><p>J3 bachelor’s programme for students entering in 2026.</p><div className="tuition-rate-columns"><div><small>Full-time</small><b>43,500 UAH</b><dl><div><dt>Semester</dt><dd>21,750 UAH</dd></div><div><dt>Month</dt><dd>4,350 UAH</dd></div></dl></div><div><small>Part-time</small><b>34,800 UAH</b><dl><div><dt>Semester</dt><dd>17,400 UAH</dd></div><div><dt>Month</dt><dd>3,480 UAH</dd></div></dl></div></div></article>
      <article className="tuition-rate-card"><span>03</span><h3>Master’s programmes</h3><p>First year on the programmes listed in the official tuition order.</p><div className="tuition-rate-columns"><div><small>Full-time</small><b>43,500 UAH</b><dl><div><dt>Semester</dt><dd>21,750 UAH</dd></div><div><dt>Month</dt><dd>4,350 UAH</dd></div></dl></div><div><small>Part-time</small><b>34,800 UAH</b><dl><div><dt>Semester</dt><dd>17,400 UAH</dd></div><div><dt>Month</dt><dd>3,480 UAH</dd></div></dl></div></div></article>
    </div><div className="tuition-source-note"><span>PDF · 4 pages</span><div><b>Official 2026/27 tuition document</b><p>The signed source remains authoritative.</p></div><a href="/documents/tuition/tuition-2026-2027.pdf" target="_blank" rel="noreferrer">Open PDF ↗</a></div></div></section>
    <section className="tuition-payment-section" id="english-payment"><div className="wrap"><div className="tuition-section-head inverse"><div><div className="idx">02 / Payment safety</div><h2>Pay only in<br />your bank app.</h2></div><p>The Academy bank details published as of 31 August 2023 are shown below. Confirm them with accounting before a first or large payment.</p></div><div className="payment-assistant"><div className="payment-assistant-form"><span className="mono">Academy banking details</span><h3>Bank transfer</h3><p><b>Recipient:</b> Academy of Labour, Social Relations and Tourism</p><p><b>EDRPOU:</b> 04641405</p><p><b>IBAN:</b> UA673052990000026005006704535</p><p><b>Bank:</b> JSC CB PRIVATBANK</p><p className="payment-privacy"><b>This website never asks for card details.</b> Do not enter a card number, CVV, banking password or SMS code on an unfamiliar page.</p></div><div className="payment-receipt"><span className="mono">Confirm before payment</span><div className="payment-amount"><small>Accounting contact</small><b>+38 096 <i>450 85 04</i></b></div><p className="payment-check">Svitlana Vasylivna, Chief Accountant. Ask the Academy to confirm the payment amount, IBAN and payment reference.</p><a className="payment-pay-now" href="https://next.privat24.ua/" target="_blank" rel="noreferrer">Continue to Privat24 payment ↗</a><a className="payment-bank-link" href="https://privatbank.ua/cpa/mobile-p24-payments" target="_blank" rel="noreferrer">Official payment instructions ↗</a></div></div></div></section>
    <section><div className="wrap"><div className="tuition-section-head"><div><div className="idx">03 / Contracts</div><h2>Official<br />templates</h2></div><p>Admissions prepares the final contract. It becomes effective after enrolment; do not send personal data through unverified forms.</p></div><div className="tuition-contract-grid"><a href="/documents/tuition/contract-paid-educational-service.docx" download><span>DOCX · 2025 template</span><div><b>Paid educational service agreement</b><p>Specialist training funded by an individual or legal entity.</p></div><strong>Download ↓</strong></a><a href="/documents/tuition/contract-education.docx" download><span>DOCX · 2025 template</span><div><b>Academy study agreement</b><p>The main agreement between the Academy and the student.</p></div><strong>Download ↓</strong></a></div></div></section>
    <section className="bigcta"><div className="wrap"><span className="mono">Need confirmation?</span><h2>Check before<br />you transfer.</h2><Link className="cta" href="/en/admissions"><span>Ask admissions</span></Link></div></section>
    <EnglishFooter />
  </main>;
}
