import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/app/components/SiteHeader";
import { EnglishFooter } from "@/app/components/EnglishFooter";

export const metadata: Metadata = {
  title: "Tuition and payment",
  description: "Official APSVT tuition rates for 2026/27, bank details, payment safety and education contract templates.",
};

export default function Page() {
  return <main id="top" className="english-page"><SiteHeader />
    <section className="tuition-hero"><div className="wrap tuition-hero-grid"><div><div className="crumb">Home / Tuition and payment</div><span className="tuition-kicker">2026/27 academic year</span><h1>Tuition<br />fees</h1><p className="lead">Official annual, semester and monthly rates for applicants and current students.</p><div className="tuition-hero-actions"><a href="#english-rates">View rates ↓</a><a href="#english-payment">Payment details →</a></div></div></div></section>
    <section id="english-rates"><div className="wrap"><div className="tuition-section-head single"><div><div className="idx">01 / New applicants</div><h2>Tuition rates<br />for applicants</h2></div></div><div className="tuition-applicant-table-wrap"><table className="tuition-applicant-table"><thead><tr><th>Level and programme</th><th>Study mode</th><th>Academic year</th><th>Semester</th><th>Month</th></tr></thead><tbody>
      <tr><th rowSpan={2} scope="rowgroup"><span>01</span><b>Most bachelor’s programmes</b><small>Law, public administration, social work, finance, management, marketing, trade, psychology and professional education / digital technologies.</small></th><td>Full-time</td><td><b>38,600 UAH</b></td><td>19,300 UAH</td><td>3,860 UAH</td></tr><tr><td>Part-time</td><td><b>30,900 UAH</b></td><td>15,450 UAH</td><td>3,090 UAH</td></tr>
      <tr><th rowSpan={2} scope="rowgroup"><span>02</span><b>Tourism and Recreation</b><small>J3 bachelor’s programme for students entering in 2026.</small></th><td>Full-time</td><td><b>43,500 UAH</b></td><td>21,750 UAH</td><td>4,350 UAH</td></tr><tr><td>Part-time</td><td><b>34,800 UAH</b></td><td>17,400 UAH</td><td>3,480 UAH</td></tr>
      <tr><th rowSpan={2} scope="rowgroup"><span>03</span><b>Master’s programmes</b><small>First year on the programmes listed in the official tuition order.</small></th><td>Full-time</td><td><b>43,500 UAH</b></td><td>21,750 UAH</td><td>4,350 UAH</td></tr><tr><td>Part-time</td><td><b>34,800 UAH</b></td><td>17,400 UAH</td><td>3,480 UAH</td></tr>
    </tbody></table></div><div className="tuition-source-note compact"><span>PDF · 4 pages</span><div><b>Official 2026/27 tuition document</b></div><a href="/documents/tuition/tuition-2026-2027.pdf" target="_blank" rel="noreferrer">Open PDF ↗</a></div></div></section>
    <section className="tuition-payment-section" id="english-payment"><div className="wrap"><div className="tuition-section-head inverse"><div><div className="idx">02 / Tuition payment</div><h2>Tuition<br />payment</h2></div><p>Confirm the amount, IBAN and payment reference with the Academy’s accounting office before a first or large payment.</p></div><div className="payment-assistant"><div className="payment-assistant-form"><span className="mono">Academy banking details</span><h3>Bank transfer</h3><p><b>Recipient:</b> Academy of Labour, Social Relations and Tourism</p><p><b>EDRPOU:</b> 04641405</p><p><b>IBAN:</b> UA673052990000026005006704535</p><p><b>Bank:</b> JSC CB PRIVATBANK</p></div><div className="payment-receipt"><span className="mono">Confirm before payment</span><div className="payment-amount"><small>Accounting contact</small><b>+38 096 <i>450 85 04</i></b></div><p className="payment-check">Svitlana Vasylivna, Chief Accountant. Ask the Academy to confirm the payment amount, IBAN and payment reference.</p><a className="payment-pay-now" href="https://www.portmone.com.ua/r3/oplata-osvity-akademiia-pratsi-sotsialnykh-vidnosyn-i-turyzmu-kyiv" target="_blank" rel="noreferrer">Pay APSVT tuition with Portmone ↗</a><small className="payment-bank-hint"><b>Recipient details are prefilled.</b> Enter the student information and amount, then verify everything before paying. Portmone’s displayed fee is 2%, minimum UAH 3.</small><a className="payment-bank-link" href="https://privatbank.ua/cpa/mobile-p24-payments" target="_blank" rel="noreferrer">Alternative: pay by IBAN in Privat24 ↗</a></div></div></div></section>
    <section><div className="wrap"><div className="tuition-section-head"><div><div className="idx">03 / Contracts</div><h2>Official<br />templates</h2></div><p>Admissions prepares the final contract. It becomes effective after enrolment; do not send personal data through unverified forms.</p></div><div className="tuition-contract-grid"><a href="/documents/tuition/contract-paid-educational-service.docx" download><span>DOCX · 2025 template</span><div><b>Paid educational service agreement</b><p>Specialist training funded by an individual or legal entity.</p></div><strong>Download ↓</strong></a><a href="/documents/tuition/contract-education.docx" download><span>DOCX · 2025 template</span><div><b>Academy study agreement</b><p>The main agreement between the Academy and the student.</p></div><strong>Download ↓</strong></a></div></div></section>
    <section className="bigcta"><div className="wrap"><span className="mono">Need confirmation?</span><h2>Check before<br />you transfer.</h2><Link className="cta" href="/en/admissions"><span>Ask admissions</span></Link></div></section>
    <EnglishFooter />
  </main>;
}
