import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/app/components/SiteHeader";
import { EnglishFooter } from "@/app/components/EnglishFooter";
import { englishPrograms } from "@/lib/english-content";

export const metadata: Metadata = { title: "Academy of Labour, Social Relations and Tourism", description: "Study, admissions, research and campus information for APSVT in Kyiv, available fully in English." };

export default function Page(){return <main id="top" className="english-page"><SiteHeader/>
  <section className="en-hero"><div className="hero-bg"><img src="/apsvt-hero.png" alt="Students at APSVT"/></div><div className="wrap"><span className="mono">Higher education · Kyiv, Ukraine</span><h1>Education with<br/><em>human impact.</em></h1><p>Study, research and build professional communities at an Academy where social responsibility meets practical expertise.</p><div><Link className="cta" href="/en/programs"><span>Explore programmes</span></Link><Link className="cta ghost" href="/en/admissions"><span>Admissions 2026</span></Link></div></div></section><div className="phero-rule"/>
  <section><div className="wrap"><div className="sec-head"><div><div className="idx">01 / Degree programmes</div><h2>Choose your direction</h2></div><Link className="sec-link" href="/en/programs">Compare all programmes →</Link></div><div className="en-programmes">{englishPrograms.map(program=><Link href={`/en/programs/${program.slug}`} key={program.slug}><span>{program.number}</span><div><small>{program.levels}</small><h3>{program.title}</h3><p>{program.code} · tuition from {program.price.replace("₴ / рік","UAH / year")}</p></div><b>→</b></Link>)}</div></div></section>
  <section className="en-split"><div className="wrap split"><div className="copy"><div className="idx">02 / Admissions</div><h2>A clear path to enrolment</h2><p className="lead">Compare programmes, prepare your education and identity documents, submit an electronic application and confirm your choice.</p><p>International applicants can request a personal document review and guidance on recognition, invitation and residence requirements.</p><Link className="cta dark" href="/en/admissions#consultation"><span>Request guidance</span></Link></div><div className="panel"><h3>Admissions team</h3><ul><li><span className="y">Phone</span><a href="tel:+380445260664">+38 (044) 526-06-64</a></li><li><span className="y">Email</span><a href="mailto:pk@socosvita.kiev.ua">pk@socosvita.kiev.ua</a></li><li><span className="y">Address</span>3-A Kiltseva Road, Kyiv</li></ul></div></div></section>
  <section className="en-dark"><div className="wrap"><div className="sec-head"><div><div className="idx">03 / Research</div><h2>Ideas across disciplines</h2></div></div><div className="en-three"><Link href="/en/research"><span>Publications</span><h3>Research catalogue</h3><p>Discover Academy authors, topics and Google Scholar profiles.</p></Link><Link href="/en/research/journals"><span>Publishing</span><h3>Academic journals</h3><p>Peer-reviewed work in economics, psychology, law and management.</p></Link><Link href="/en/research/conferences"><span>Community</span><h3>Conferences</h3><p>International dialogue on labour, law and social transformation.</p></Link></div></div></section>
  <section><div className="wrap split"><div className="ph tall"><img src="https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1200&q=90&auto=format&fit=crop" alt="University library"/></div><div className="copy"><div className="idx">04 / Campus</div><h2>Study and live in one place</h2><p className="lead">The Kyiv campus brings together classrooms, a library, laboratories, a legal clinic, student housing and shared project spaces.</p><Link className="cta dark" href="/en/facilities"><span>Explore campus</span></Link></div></div></section>
  <section className="bigcta"><div className="wrap"><span className="mono">Full English website</span><h2>Every section, now in English.</h2><p>Programmes, people, admissions, schedules, research, facilities, events, stories and news all have dedicated English routes.</p><Link className="cta" href="/en/about"><span>Discover the Academy</span></Link></div></section>
  <EnglishFooter/></main>}
