import type { Metadata } from "next";
import Link from "next/link";
import { programs } from "@/lib/programs";

export const metadata: Metadata = { title: "Academy of Labour, Social Relations and Tourism", description: "English overview of APSVT programmes, admissions, research and campus in Kyiv." };
const programmeTitles: Record<string, string> = { psychology: "Psychology", finance: "Finance, Banking and Insurance", management: "Management", "public-administration": "Public Administration", marketing: "Marketing", trade: "Trade and Entrepreneurship", law: "Law", "social-work": "Social Work and Counselling", tourism: "Tourism and Recreation" };
export default function Page() { return <main id="top" className="english-page"><header className="english-header"><div className="wrap"><Link className="brand" href="/en"><span className="brand-mark"><i>A</i></span><span className="brand-name">Academy of Labour,<br />Social Relations and Tourism<em>Kyiv · established 1993</em></span></Link><nav aria-label="English navigation"><a href="#programmes">Programmes</a><a href="#admissions">Admissions</a><a href="#research">Research</a><a href="#campus">Campus</a><a href="#contacts">Contacts</a></nav><Link className="lang-toggle" href="/">UA</Link></div></header>
  <section className="en-hero"><div className="hero-bg"><img src="/apsvt-hero.png" alt="Students at APSVT" /></div><div className="wrap"><span className="mono">Higher education · Kyiv, Ukraine</span><h1>Education with<br /><em>human impact.</em></h1><p>Study, research and build professional communities at an Academy where social responsibility meets practical expertise.</p><div><a className="cta" href="#programmes"><span>Explore programmes</span></a><a className="cta ghost" href="#admissions"><span>Admissions 2026</span></a></div></div></section><div className="phero-rule" />
  <section id="programmes"><div className="wrap"><div className="sec-head"><div><div className="idx">01 / Degree programmes</div><h2>Choose your direction</h2></div></div><div className="en-programmes">{programs.map((program) => <Link href={`/programs/${program.slug}`} key={program.slug}><span>{program.number}</span><div><small>{program.levels.replace("Бакалавр", "Bachelor").replace("Магістр", "Master")}</small><h3>{programmeTitles[program.slug]}</h3><p>{program.code} · tuition from {program.price}</p></div><b>→</b></Link>)}</div></div></section>
  <section id="admissions" className="en-split"><div className="wrap split"><div className="copy"><div className="idx">02 / Admissions</div><h2>A clear path to enrolment</h2><p className="lead">Compare programmes, prepare your education and identity documents, submit an electronic application and confirm your choice.</p><p>International applicants can request a personal document review and guidance on recognition, invitation and residence requirements.</p><Link className="cta dark" href="/admissions#consultation"><span>Request guidance</span></Link></div><div className="panel"><h3>Admissions team</h3><ul><li><span className="y">Phone</span><a href="tel:+380445260664">+38 (044) 526-06-64</a></li><li><span className="y">Email</span><a href="mailto:pk@socosvita.kiev.ua">pk@socosvita.kiev.ua</a></li><li><span className="y">Address</span>3-A Kiltseva Road, Kyiv</li></ul></div></div></section>
  <section id="research" className="en-dark"><div className="wrap"><div className="sec-head"><div><div className="idx">03 / Research</div><h2>Ideas across disciplines</h2></div></div><div className="en-three"><Link href="/research"><span>Publications</span><h3>Research catalogue</h3><p>Search Academy authors, topics and Google Scholar profiles.</p></Link><Link href="/research/journals"><span>Publishing</span><h3>Academic journals</h3><p>Peer-reviewed work in economics, psychology and management.</p></Link><Link href="/research/conferences"><span>Community</span><h3>Conferences</h3><p>International dialogue on labour, law and social transformation.</p></Link></div></div></section>
  <section id="campus"><div className="wrap split"><div className="ph tall"><img src="https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=1200&q=90&auto=format&fit=crop" alt="University library" /></div><div className="copy"><div className="idx">04 / Campus</div><h2>Study and live in one place</h2><p className="lead">The Kyiv campus brings together classrooms, a library, laboratories, a legal clinic, student housing and shared project spaces.</p><Link className="cta dark" href="/facilities"><span>Explore campus</span></Link></div></div></section>
  <footer id="contacts" className="en-footer"><div className="wrap"><div><b>Academy of Labour, Social Relations and Tourism</b><p>3-A Kiltseva Road, Kyiv, 03187, Ukraine</p></div><div><a href="tel:+380445260664">+38 (044) 526-06-64</a><a href="mailto:info@socosvita.kiev.ua">info@socosvita.kiev.ua</a></div><a href="#top">Back to top ↑</a></div></footer>
  </main> }
