import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";
import { marketingConferenceProceedings } from "../journals/MarketingPublications";

export const metadata: Metadata = { title: "Наукові конференції", description: "Архів конференцій АПСВТ за 2021–2026 роки, інформаційні листи, програми та збірники." };

const conferences = [
  { year: "2026", date: "8 жовтня", title: "Mental health: особистісний та організаційний виміри", text: "ІІ Міжнародна науково-практична конференція факультету психології та соціального розвитку.", links: [["Сторінка конференції", "/news/mental-health-conference-2026"], ["Програма конференції", "/documents/news/mental-health-conference-2026-program.pdf"]] },
  { year: "2026", date: "21 травня", title: "Ринок праці: інновації, трансформації та розвиток міжнародного співробітництва", text: "Міжнародна науково-практична конференція про зайнятість, соціальні технології, право та міжнародну співпрацю.", links: [["Збірник тез", "/documents/research/psychology-faculty/conference-proceedings/labour-market-2026.pdf"]] },
  { year: "2026", date: "9–10 квітня", title: "Освіта, Право та Публічне управління — новітні тенденції розвитку", text: "V Міжнародна науково-практична конференція ELPA–NDT за участю партнерів з України, Іраку та Польщі.", links: [["Сторінка конференції", "https://www.socosvita.kiev.ua/node/3323"], ["Збірник тез", "https://www.socosvita.kiev.ua/sites/default/files/%20%D1%82%D0%B5%D0%B7_ELPA%202026.pdf"]] },
  { year: "2026", date: "10 березня", title: "Науковий вимір осмислення та пошуку оптимальних моделей розвитку України", text: "ІІІ Міжнародна конференція з маркетингових, економічних, фінансових, управлінських і правових аспектів розвитку України.", links: [["Інформація та лист", "https://www.socosvita.kiev.ua/node/3277"]] },
  { year: "2025", date: "15 травня", title: "Ринок праці: пріоритети та стратегії повоєнної європейської інтеграції", text: "Міжнародна конференція про відновлення ринку праці, європейську інтеграцію та роль соціального діалогу.", links: [["Збірник тез", "/documents/research/psychology-faculty/conference-proceedings/labour-market-2025.pdf"]] },
  { year: "2025", date: "19 березня", title: "Науковий вимір осмислення та пошуку оптимальних моделей розвитку України", text: "ІІ Міжнародна конференція кафедри маркетингу та закладів-партнерів.", links: [["Інформаційний лист", "https://www.socosvita.kiev.ua/node/3126"], ["Збірник матеріалів · 377 сторінок", "/documents/archive/old-site/conference-proceedings-2025.pdf"]] },
  { year: "2024", date: "16 травня", title: "Ринок праці: можливості та вектори розвитку у глобалізованому світі", text: "Міжнародна конференція з економічного, соціального, психологічного та правового напрямів.", links: [["Збірник тез", "/documents/research/psychology-faculty/conference-proceedings/labour-market-2024.pdf"]] },
  { year: "2024", date: "4–5 березня", title: "Науковий вимір осмислення та пошуку оптимальних моделей розвитку України", text: "Міжнародна науково-практична конференція з маркетингу, економіки, фінансів та управління.", links: [["Інформаційний лист", "https://www.socosvita.kiev.ua/sites/default/files/%D0%BB%D0%B8%D1%81%D1%82%20%D0%BA%D0%B0%D1%84.%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%82%D0%B8%D0%BD%D0%B3_1.03.24%20%282%29.pdf"]] },
  { year: "2023", date: "18 травня", title: "Ринок праці: досягнення, виклики та перспективи у національному та європейському просторі", text: "Ювілейна міжнародна конференція до 30-річчя Академії, що об’єднала науковців, практиків і профспілкових діячів.", links: [["Збірник тез", "/documents/research/psychology-faculty/conference-proceedings/labour-market-2023.pdf"]] },
] as const;

const lawFacultyProceedings = [
  { year: "2026", date: "9–10 квітня", title: "Освіта, Право та Публічне управління — новітні тенденції розвитку (ELPA–NDT)", meta: "V Міжнародна науково-практична конференція · 84 сторінки", href: "/documents/research/law-faculty/conference-proceedings/elpa-ndt-2026.pdf", format: "PDF" },
  { year: "2025", date: "5 грудня", title: "Муніципальна реформа в контексті євроінтеграції України", meta: "Одинадцята щорічна всеукраїнська науково-практична конференція · 210 сторінок", href: "/documents/research/law-faculty/conference-proceedings/municipal-reform-2025-12-05.pdf", format: "PDF" },
  { year: "2025", date: "17 січня", title: "Муніципальна реформа в контексті євроінтеграції України", meta: "Десята щорічна всеукраїнська науково-практична конференція · 229 сторінок", href: "/documents/research/law-faculty/conference-proceedings/municipal-reform-2025-01-17.pdf", format: "PDF" },
  { year: "2024", date: "6 вересня", title: "Муніципальна реформа в контексті євроінтеграції України", meta: "Дев’ята щорічна всеукраїнська науково-практична конференція · 366 сторінок", href: "/documents/research/law-faculty/conference-proceedings/municipal-reform-2024-09-06.pdf", format: "PDF" },
  { year: "2023", date: "22 грудня", title: "Муніципальна реформа в контексті євроінтеграції України", meta: "Восьма щорічна всеукраїнська науково-практична конференція · 438 сторінок", href: "/documents/research/law-faculty/conference-proceedings/municipal-reform-2023-12-22.pdf", format: "PDF" },
  { year: "2023", date: "25 серпня", title: "Муніципальна реформа в контексті євроінтеграції України", meta: "Сьома щорічна всеукраїнська науково-практична конференція · 304 сторінки", href: "/documents/research/law-faculty/conference-proceedings/municipal-reform-2023-08-25.pdf", format: "PDF" },
  { year: "2022", date: "23 грудня", title: "Муніципальна реформа в контексті євроінтеграції України", meta: "Шоста щорічна всеукраїнська науково-практична конференція · 333 сторінки", href: "/documents/research/law-faculty/conference-proceedings/municipal-reform-2022-12-23.pdf", format: "PDF" },
  { year: "2022", date: "7 жовтня", title: "Юридична наука сьогодення: виклики і загрози", meta: "Всеукраїнська науково-практична конференція · 104 сторінки", href: "/documents/research/law-faculty/conference-proceedings/legal-science-2022-10-07.pdf", format: "PDF" },
  { year: "2021", date: "10 грудня", title: "Муніципальна реформа в контексті євроінтеграції України", meta: "П’ята щорічна всеукраїнська науково-практична конференція", href: "/documents/research/law-faculty/conference-proceedings/municipal-reform-2021-12-10.docx", format: "DOCX" },
] as const;

export default function Page() { return <main id="top"><SiteHeader /><section className="phero"><div className="wrap"><div className="crumb">Наука / Конференції</div><h1>Місце для<br />наукової розмови</h1><p className="lead">Відновлений архів конференцій Академії за 2021–2026 роки: анонси, інформаційні листи, програми, підсумки та збірники.</p></div></section><div className="phero-rule" />
<section className="marketing-publications" id="marketing-proceedings"><div className="wrap"><div className="marketing-publications-head"><div><div className="idx">01 / Повні тексти</div><h2>Збірники кафедри маркетингу</h2></div><p>Три повні збірники матеріалів міжнародних конференцій кафедри за 2024, 2025 і 2026 роки — з титульними сторінками, бібліографічними даними та DOI.</p></div><div className="marketing-conference-grid">{marketingConferenceProceedings.map((publication) => <article className="marketing-conference-card" key={publication.year}><a className="marketing-conference-cover" href={publication.href} target="_blank" rel="noreferrer" aria-label={`Відкрити збірник за ${publication.year} рік`}><img src={publication.cover} alt={`Титульна сторінка збірника конференції ${publication.year} року`} /></a><div className="marketing-conference-body"><div className="marketing-publication-meta"><span>{publication.year}</span><small>{publication.edition}</small></div><h3>{publication.title}</h3><p>{publication.description}</p><dl><div><dt>Дата</dt><dd>{publication.date}</dd></div><div><dt>Обсяг</dt><dd>{publication.pages}</dd></div><div><dt>Видання</dt><dd>{publication.isbn}</dd></div></dl><div className="marketing-publication-footer"><span>Київ · АПСВТ</span><div><a href={publication.href} target="_blank" rel="noreferrer">Відкрити PDF ↗</a><a href={publication.doi} target="_blank" rel="noreferrer">DOI ↗</a></div></div></div></article>)}</div></div></section>
<section id="law-faculty-proceedings"><div className="wrap"><div className="sec-head"><div><div className="idx">02 / Юридичний факультет</div><h2>Збірники конференцій</h2></div><p>Повні матеріали конференцій юридичного факультету за 2021–2026 роки. Назви, дати й обсяг наведено за титульними сторінками видань.</p></div><div className="conference-list conference-archive-list">{lawFacultyProceedings.map((item, index) => <article key={item.href}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{item.year} · {item.date}</small><h2>{item.title}</h2><p>{item.meta}</p><div className="conference-links"><a href={item.href} target="_blank" rel="noreferrer">Відкрити {item.format} ↗</a></div></div></article>)}</div></div></section>
<section><div className="wrap"><div className="sec-head"><div><div className="idx">03 / Відновлений архів</div><h2>Конференції Академії</h2></div><p>Новіші матеріали розміщено першими. Документи відкриваються в окремій вкладці.</p></div><div className="conference-list conference-archive-list">{conferences.map((item, index) => <article key={`${item.year}-${item.title}`}><span>{String(index + 1).padStart(2, "0")}</span><div><small>Архів {item.year} · {item.date}</small><h2>{item.title}</h2><p>{item.text}</p><div className="conference-links">{item.links.map(([label, href]) => <a href={href} target="_blank" rel="noreferrer" key={href}>{label} ↗</a>)}</div></div></article>)}</div></div></section><section className="soft"><div className="wrap split"><div className="copy"><div className="idx">04 / Участь</div><h2>Від тези до дискусії</h2><p className="lead">Анонс кожної конференції містить тематичні секції, вимоги до матеріалів, дедлайн і формат участі.</p><p>Електронні збірники зберігаються у науковому репозиторії Академії.</p><Link className="cta dark" href="/events#registration"><span>Реєстрація на події</span></Link></div><div className="conference-path"><div><b>01</b><span>Оберіть секцію</span></div><div><b>02</b><span>Подайте тему й анотацію</span></div><div><b>03</b><span>Отримайте рішення оргкомітету</span></div><div><b>04</b><span>Виступіть і отримайте сертифікат</span></div></div></div></section><SiteFooter /></main> }
