import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";

export const metadata: Metadata = { title: "Наукові конференції", description: "Архів конференцій АПСВТ за 2023–2026 роки, інформаційні листи, програми та збірники." };

const conferences = [
  { year: "2026", date: "21 травня", title: "Ринок праці: інновації, трансформації та розвиток міжнародного співробітництва", text: "Міжнародна науково-практична конференція про зайнятість, соціальні технології, право та міжнародну співпрацю.", links: [["Інформаційний лист і програма", "https://www.socosvita.kiev.ua/node/3307"]] },
  { year: "2026", date: "9–10 квітня", title: "Освіта, Право та Публічне управління — новітні тенденції розвитку", text: "V Міжнародна науково-практична конференція ELPA–NDT за участю партнерів з України, Іраку та Польщі.", links: [["Сторінка конференції", "https://www.socosvita.kiev.ua/node/3323"], ["Збірник тез", "https://www.socosvita.kiev.ua/sites/default/files/%20%D1%82%D0%B5%D0%B7_ELPA%202026.pdf"]] },
  { year: "2026", date: "10 березня", title: "Науковий вимір осмислення та пошуку оптимальних моделей розвитку України", text: "ІІІ Міжнародна конференція з маркетингових, економічних, фінансових, управлінських і правових аспектів розвитку України.", links: [["Інформація та лист", "https://www.socosvita.kiev.ua/node/3277"]] },
  { year: "2025", date: "15 травня", title: "Ринок праці: пріоритети та стратегії повоєнної європейської інтеграції", text: "Міжнародна конференція про відновлення ринку праці, європейську інтеграцію та роль соціального діалогу.", links: [["Інформаційний лист", "https://www.socosvita.kiev.ua/node/3128"], ["Підсумки конференції", "https://www.socosvita.kiev.ua/node/3238"]] },
  { year: "2025", date: "19 березня", title: "Науковий вимір осмислення та пошуку оптимальних моделей розвитку України", text: "ІІ Міжнародна конференція кафедри маркетингу та закладів-партнерів.", links: [["Інформаційний лист", "https://www.socosvita.kiev.ua/node/3126"], ["Збірник матеріалів · 377 сторінок", "/documents/archive/old-site/conference-proceedings-2025.pdf"]] },
  { year: "2024", date: "16 травня", title: "Ринок праці: можливості та вектори розвитку у глобалізованому світі", text: "Міжнародна конференція з економічного, соціального, психологічного та правового напрямів.", links: [["Інформаційний лист і програма", "https://www.socosvita.kiev.ua/node/2927"], ["Підсумки конференції", "https://www.socosvita.kiev.ua/node/2966"]] },
  { year: "2024", date: "4–5 березня", title: "Науковий вимір осмислення та пошуку оптимальних моделей розвитку України", text: "Міжнародна науково-практична конференція з маркетингу, економіки, фінансів та управління.", links: [["Інформаційний лист", "https://www.socosvita.kiev.ua/sites/default/files/%D0%BB%D0%B8%D1%81%D1%82%20%D0%BA%D0%B0%D1%84.%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%82%D0%B8%D0%BD%D0%B3_1.03.24%20%282%29.pdf"]] },
  { year: "2023", date: "18 травня", title: "Ринок праці: досягнення, виклики та перспективи у національному та європейському просторі", text: "Ювілейна міжнародна конференція до 30-річчя Академії, що об’єднала науковців, практиків і профспілкових діячів.", links: [["Інформаційний лист", "https://www.socosvita.kiev.ua/node/2750"], ["Підсумки конференції", "https://www.socosvita.kiev.ua/node/2860"]] },
] as const;

export default function Page() { return <main id="top"><SiteHeader /><section className="phero"><div className="wrap"><div className="crumb">Наука / Конференції</div><h1>Місце для<br />наукової розмови</h1><p className="lead">Відновлений архів конференцій Академії за 2023–2026 роки: анонси, інформаційні листи, програми, підсумки та збірники.</p></div></section><div className="phero-rule" /><section><div className="wrap"><div className="sec-head"><div><div className="idx">01 / Відновлений архів</div><h2>Конференції Академії</h2></div><p>Новіші матеріали розміщено першими. Документи відкриваються в окремій вкладці.</p></div><div className="conference-list conference-archive-list">{conferences.map((item, index) => <article key={`${item.year}-${item.title}`}><span>{String(index + 1).padStart(2, "0")}</span><div><small>Архів {item.year} · {item.date}</small><h2>{item.title}</h2><p>{item.text}</p><div className="conference-links">{item.links.map(([label, href]) => <a href={href} target="_blank" rel="noreferrer" key={href}>{label} ↗</a>)}</div></div></article>)}</div></div></section><section className="soft"><div className="wrap split"><div className="copy"><div className="idx">02 / Участь</div><h2>Від тези до дискусії</h2><p className="lead">Анонс кожної конференції містить тематичні секції, вимоги до матеріалів, дедлайн і формат участі.</p><p>Електронні збірники зберігаються у науковому репозиторії Академії.</p><Link className="cta dark" href="/events#registration"><span>Реєстрація на події</span></Link></div><div className="conference-path"><div><b>01</b><span>Оберіть секцію</span></div><div><b>02</b><span>Подайте тему й анотацію</span></div><div><b>03</b><span>Отримайте рішення оргкомітету</span></div><div><b>04</b><span>Виступіть і отримайте сертифікат</span></div></div></div></section><SiteFooter /></main> }
