import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";

export const metadata: Metadata = { title: "Наукові конференції", description: "Конференції, тематичні напрями та наукові збірники АПСВТ." };
const conferences = [
  { date: "21 травня 2026", status: "Архів 2026", title: "Ринок праці: інновації, трансформації та розвиток міжнародного співробітництва", text: "Міжнародна науково-практична конференція про зайнятість, соціальні технології, право та міжнародну співпрацю. Сертифікат участі — 0,5 кредита ЄКТС / 15 годин." },
  { date: "10 березня 2026", status: "Архів 2026", title: "Науковий вимір розвитку України", text: "Третя міжнародна конференція з маркетингових, економічних, фінансових, управлінських і правових аспектів розвитку України." },
  { date: "Наступний анонс", status: "Готується", title: "Конференційний сезон 2027", text: "Теми, строки подання матеріалів і формат участі будуть опубліковані після затвердження оргкомітетом." },
];
export default function Page() { return <main id="top"><SiteHeader /><section className="phero"><div className="wrap"><div className="crumb">Наука / Конференції</div><h1>Місце для<br />наукової розмови</h1><p className="lead">Міжнародні конференції Академії об’єднують дослідників, студентів, практиків та партнерські університети.</p></div></section><div className="phero-rule" /><section><div className="wrap"><div className="sec-head"><div><div className="idx">01 / Календар і архів</div><h2>Конференції Академії</h2></div></div><div className="conference-list">{conferences.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{item.status} · {item.date}</small><h2>{item.title}</h2><p>{item.text}</p></div></article>)}</div></div></section><section className="soft"><div className="wrap split"><div className="copy"><div className="idx">02 / Участь</div><h2>Від тези до дискусії</h2><p className="lead">Анонс кожної конференції містить тематичні секції, вимоги до матеріалів, дедлайн і формат участі.</p><p>Електронні збірники зберігаються у науковому репозиторії Академії. Посилання на програму та онлайн-засідання надсилаються зареєстрованим учасникам.</p><Link className="cta dark" href="/events#registration"><span>Реєстрація на події</span></Link></div><div className="conference-path"><div><b>01</b><span>Оберіть секцію</span></div><div><b>02</b><span>Подайте тему й анотацію</span></div><div><b>03</b><span>Отримайте рішення оргкомітету</span></div><div><b>04</b><span>Виступіть і отримайте сертифікат</span></div></div></div></section><SiteFooter /></main> }
