import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";
import { LawFacultyTeam } from "../../components/LawFacultyTeam";
import { PageDocuments } from "../../components/PageDocuments";
import { DepartmentEditorialContent } from "../../components/DepartmentEditorialContent";
import { getDepartmentEntries } from "@/lib/department-content";
import { SectionHub, type SectionHubItem } from "../../components/SectionHub";
import { EducationQualitySection } from "../../components/EducationQualitySection";
import { AcademicNews } from "../../components/AcademicNews";
import { AcademicProfileCard } from "../../components/AcademicProfileCard";

export const metadata: Metadata = {
  title: "Юридичний факультет",
  description: "Структура юридичного факультету АПСВТ: керівництво, кафедри, освітні програми, практика, наука, документи та студентські ініціативи.",
};

const departments = [
  ["01", "Кафедра конституційного, адміністративного та фінансового права", "Конституційне, адміністративне, фінансове й муніципальне право.", "/departments/constitutional-law"],
  ["02", "Кафедра публічного управління та адміністрування", "Публічна політика, служба, розвиток громад і соціальний діалог.", "/programs/public-administration#department"],
  ["03", "Кафедра цивільного, трудового та господарського права", "Цивільне, господарське, трудове право та судовий захист.", "/departments/private-law"],
  ["04", "Кафедра кримінального права, процесу та криміналістики", "Кримінальне право, процес, захист прав людини та криміналістика.", "/departments/criminal-law"],
] as const;

const facultySections: readonly SectionHubItem[] = [
  { id: "faculty-about", index: "01", title: "Про факультет", description: "Історія, місія, пріоритети та структура.", icon: "F", aliases: ["faculty-history", "faculty-mission", "faculty-structure"] },
  { id: "faculty-leadership", index: "02", title: "Керівництво та деканат", description: "Декан, заступники, деканат і документи.", icon: "DEC", aliases: ["faculty-dean", "faculty-dean-office"] },
  { id: "departments", index: "03", title: "Кафедри", description: "Чотири академічні підрозділи факультету.", icon: "4" },
  { id: "faculty-legal-clinic", index: "04", title: "Юридична клініка «Феміда»", description: "Правнича допомога, навчання та супервізія.", icon: "LAW" },
  { id: "faculty-forensic-lab", index: "05", title: "Навчальна лабораторія криміналістики", description: "Практична підготовка та моделювання процесуальних дій.", icon: "LAB" },
  { id: "faculty-practice-bases", index: "06", title: "Бази практики", description: "Професійні установи та практична підготовка.", icon: "PR" },
  { id: "faculty-science-clubs", index: "07", title: "Наукові гуртки", description: "Студентські дослідження, зустрічі та проєкти.", icon: "CLUB" },
  { id: "municipal-law-school", index: "08", title: "Наукова школа муніципального права", description: "Дослідження місцевого самоврядування та децентралізації.", icon: "SCI" },
  { id: "faculty-council", index: "09", title: "Вчена рада", description: "Склад, положення, плани, засідання й протоколи.", icon: "RAD" },
  { id: "faculty-student-government", index: "10", title: "Студентське самоврядування", description: "Студентська рада, проєкти, новини й контакти.", icon: "STU" },
  { id: "law-teachers", index: "11", title: "Колектив факультету", description: "Керівництво, викладачі, науковці та практики.", icon: "TEAM" },
  { id: "faculty-programmes", index: "12", title: "Освітні програми", description: "D8 «Право», D4 «Публічне управління» та PhD.", icon: "OP", aliases: ["law-levels"] },
  { id: "faculty-discussion", index: "13", title: "Громадське обговорення освітніх програм", description: "Проєкти програм, пропозиції та результати розгляду.", icon: "DIA" },
  { id: "faculty-repository", index: "14", title: "Репозитарій", description: "Кваліфікаційні роботи D8 і D4 з пошуком.", icon: "REP" },
  { id: "faculty-quality", index: "15", title: "Якість освіти", description: "Моніторинг, оцінювання та офіційні документи.", icon: "✓" },
  { id: "department-news", index: "16", title: "Новини факультету", description: "Події, публікації та матеріали кафедр.", icon: "NEWS" },
];

const practiceCategories = ["Суди", "Органи прокуратури", "Органи Національної поліції", "Адвокатура", "Органи державної влади", "Місцеве самоврядування", "Юридичні компанії", "Підприємства й організації"];

export default async function Page() {
  const departmentEntries = await getDepartmentEntries("/departments/law-faculty");

  return <main id="top"><SiteHeader />
    <section className="law-faculty-hero"><div className="law-faculty-hero-image"><Image src="https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1800&q=92&auto=format&fit=crop" alt="Правнича освіта" fill sizes="(max-width: 720px) 100vw, 56vw" priority /></div><div className="wrap law-faculty-hero-copy"><Link href="/departments">← Усі факультети й кафедри</Link><span>ЮФ · з 1994 року</span><h1>Юридичний<br /><em>факультет</em></h1><p>Фундаментальна правнича освіта, клінічна практика, криміналістична лабораторія та дослідження, що працюють для людини й держави.</p><div><b>4</b><span>кафедри</span><b>2</b><span>практичні осередки</span></div></div></section><div className="hero-rule" />

    <SectionHub sections={facultySections} eyebrow="Структура юридичного факультету" description="Оберіть потрібний напрям. Відкриється тільки один розділ, а вкладені картки приведуть до конкретної кафедри, програми, документа або матеріалу.">

      <section className="law-faculty-intro" id="faculty-about"><div className="wrap law-faculty-intro-grid"><div><div className="idx">01 / Про факультет</div><h2>Від першого набору до правничої екосистеми</h2></div><div><p className="program-lede">Становлення факультету розпочалося з першого набору студентів у 1994 році. Сьогодні він готує практиків для судових, правозахисних і правоохоронних установ, органів влади, місцевого самоврядування та юридичного бізнесу.</p><p>До викладання залучені науковці та юристи-практики. Виїзні заняття, гостьові лекції, клінічна робота й лабораторні симуляції перетворюють теорію на професійну дію.</p><nav className="faculty-subsection-nav" aria-label="Про факультет: підрозділи"><a href="#faculty-about"><b>Загальна інформація</b><span>01</span></a><a href="#faculty-history" id="faculty-history"><b>Історія факультету</b><span>02</span></a><a href="#faculty-mission" id="faculty-mission"><b>Місія та стратегічні пріоритети</b><span>03</span></a><a href="#faculty-structure" id="faculty-structure"><b>Структура факультету</b><span>04</span></a></nav><div className="law-faculty-milestones"><span><b>1994</b>перший набір студентів</span><span><b>2014</b>відкриття клініки «Феміда»</span><span><b>3</b>рівні вищої освіти</span></div></div></div></section>

      <section className="faculty-structure-section faculty-leadership" id="faculty-leadership"><div className="wrap"><div className="sec-head"><div><div className="idx">02 / Керівництво та деканат</div><h2>Команда, що координує факультет</h2></div><p>Профілі керівництва, функції деканату та офіційні матеріали зібрано в одному розділі.</p></div><div className="faculty-leadership-grid" id="faculty-dean"><AcademicProfileCard badge="Декан факультету" person={{ name: "Ярослав Журавель", role: "доктор юридичних наук, професор, декан юридичного факультету", summary: "Координує освітню, наукову й організаційну роботу факультету. Досліджує муніципальне право, децентралізацію та місцеве самоврядування.", image: "/people/law/yaroslav-zhuravel.webp", tags: ["муніципальне право", "децентралізація", "управління факультетом"], links: [{ label: "ORCID", href: "https://orcid.org/0000-0002-7623-9144" }, { label: "Google Scholar", href: "https://scholar.google.com/citations?user=d_ca1TwAAAAJ&hl=uk" }] }} /><AcademicProfileCard badge="Заступниця декана" person={{ name: "Світлана Шевченко", role: "старша викладачка, заступниця декана з виховної роботи", summary: "Працює в Академії з 1995 року. Супроводжує виховну й комунікаційну роботу факультету та викладає юридичну деонтологію і професійну етику.", image: "/people/law/svitlana-shevchenko.webp", tags: ["виховна робота", "юридична деонтологія", "професійна комунікація"], links: [{ label: "ORCID", href: "https://orcid.org/0000-0001-5932-7487" }] }} /><aside className="faculty-office-card" id="faculty-dean-office"><span>Деканат</span><h3>Організаційна підтримка студентів і викладачів</h3><ul><li>організація освітнього процесу;</li><li>комунікація з кафедрами;</li><li>практична підготовка;</li><li>студентські звернення;</li><li>документообіг факультету.</li></ul><Link href="/contacts">Контакти Академії →</Link></aside></div></div></section>

      <section className="law-faculty-departments" id="departments"><div className="wrap"><div className="sec-head"><div><div className="idx">03 / Академічна структура</div><h2>Чотири кафедри — єдина траєкторія</h2></div><p>Кожна картка відкриває сторінку кафедри з командою, освітньою та науковою діяльністю, матеріалами й контактами.</p></div><div className="law-department-grid">{departments.map(([number, title, text, href]) => <Link href={href} key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p><b>Відкрити кафедру →</b></Link>)}</div></div></section>

      <section className="law-practice-showcase" id="faculty-legal-clinic"><div className="wrap"><div className="law-practice-head"><div><div className="idx">04 / Юридична клініка «Феміда»</div><h2>Правнича допомога під супервізією</h2></div><p>Інтерв’ювання клієнта, правовий аналіз, підготовка відповіді, правопросвітницькі заходи та професійна етика.</p></div><div className="law-practice-grid"><Link href="/programs/law/legal-clinic"><span>01</span><small>Окрема сторінка</small><h3>Юридична клініка «Феміда»</h3><p>Команда, напрями роботи, навчальна діяльність, новини, документи та контакти.</p><b>Відкрити сторінку клініки →</b></Link></div></div></section>

      <section className="law-practice-showcase" id="faculty-forensic-lab"><div className="wrap"><div className="law-practice-head"><div><div className="idx">05 / Навчальна лабораторія криміналістики</div><h2>Практика процесуальних дій</h2></div><p>Матеріально-технічне забезпечення, фіксація слідів, аналіз документів, моделювання слідчих дій та наукова робота.</p></div><div className="law-practice-grid"><Link href="/programs/law/forensic-laboratory"><span>01</span><small>Окрема сторінка</small><h3>Навчальна лабораторія криміналістики</h3><p>Обладнання, напрями підготовки, заняття, новини, документи та контакти.</p><b>Відкрити сторінку лабораторії →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-practice-bases" id="faculty-practice-bases"><div className="wrap"><div className="sec-head"><div><div className="idx">06 / Бази практики</div><h2>Професійне середовище факультету</h2></div><p>Конкретну базу та строк практики факультет підтверджує для відповідного навчального року, договору й індивідуальної траєкторії студента.</p></div><div className="faculty-category-grid">{practiceCategories.map((category, index) => <Link href="/departments/law-faculty#faculty-practice-bases" key={category}><span>{String(index + 1).padStart(2, "0")}</span><b>{category}</b><i>↗</i></Link>)}</div><div className="faculty-action-note"><p><b>Студентам</b> Інформація про направлення, керівника та звітність з практики надається кафедрою.</p><Link href="/contacts">Уточнити контакти →</Link></div></div></section>

      <section className="faculty-structure-section faculty-science-directory" id="faculty-science-clubs"><div className="wrap"><div className="sec-head"><div><div className="idx">07 / Наукові гуртки</div><h2>Студентські дослідження окремо</h2></div><p>Гуртки не об’єднані з науковою школою: тут публікуються учасники, плани, зустрічі, теми й результати студентських проєктів.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-blue" href="/departments/constitutional-law#science-clubs"><span>01 / Гурток</span><h3>Історико-правовий гурток «Фенікс»</h3><p>Зустрічі, дослідницькі напрями, плани роботи та студентські наукові проєкти.</p><b>Відкрити сторінку кафедри →</b></Link><Link className="faculty-link-card" href="/research/conferences"><span>02 / Події</span><h3>Конференції та наукові заходи</h3><p>Календар дискусій, круглих столів і презентацій результатів.</p><b>Перейти до конференцій →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-science-directory" id="municipal-law-school"><div className="wrap"><div className="sec-head"><div><div className="idx">08 / Наукова школа муніципального права</div><h2>Місцеве самоврядування та децентралізація</h2></div><p>Окремий розділ для історії школи, учасників, досліджень, публікацій і конкурсних робіт.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-gold" href="/departments/constitutional-law#local-government"><span>01 / Наукова школа</span><h3>Школа муніципального права</h3><p>Дослідження місцевого самоврядування, муніципальної правотворчості та розвитку громад.</p><b>Відкрити напрям →</b></Link><Link className="faculty-link-card" href="/research/journals"><span>02 / Публікації</span><h3>Наукові видання</h3><p>Журнали, збірники, монографії та відкриті дослідження.</p><b>Перейти до видань →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-governance" id="faculty-council"><div className="wrap"><div className="sec-head"><div><div className="idx">09 / Вчена рада</div><h2>Колегіальні рішення факультету</h2></div><p>Склад, положення, план роботи, засідання, рішення, протоколи та архів за роками.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-dark" href="/documents#governance"><span>01 / Документи</span><h3>Вчена рада юридичного факультету</h3><p>Офіційні матеріали колегіального органу.</p><b>Перейти до документів →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-governance" id="faculty-student-government"><div className="wrap"><div className="sec-head"><div><div className="idx">10 / Студентське самоврядування</div><h2>Участь студентів у житті факультету</h2></div><p>Студентська рада, її склад, проєкти, ініціативи, новини, події та контакти публікуються окремо від Вченої ради.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-gold" href="/students/council"><span>01 / Студенти</span><h3>Студентська рада</h3><p>Команда, проєкти, ініціативи, події та контакти.</p><b>Відкрити студентську раду →</b></Link></div></div></section>

      <div><LawFacultyTeam /><section className="faculty-team-directory"><div className="wrap"><div className="sec-head"><div><div className="idx">11 / Колектив факультету</div><h2>Знайдіть викладача за підрозділом</h2></div><p>Повні й актуальні профілі фахівців інших кафедр відкриваються на їхніх сторінках.</p></div><div className="faculty-category-grid">{departments.map(([number, title, , href]) => <Link href={href} key={number}><span>{number}</span><b>{title.replace("Кафедра ", "")}</b><i>↗</i></Link>)}</div></div></section></div>

      <section className="faculty-programmes" id="faculty-programmes"><div className="wrap"><div className="sec-head"><div><div className="idx">12 / Освітні програми</div><h2>Освітні траєкторії факультету</h2></div><p>Картка «Право» тепер залишається в межах юридичного факультету й одразу показує рівні освіти. Сторінка кафедри відкривається окремо.</p></div><div className="faculty-programme-grid"><Link href="/departments/law-faculty#law-levels"><span>01</span><b>D8</b><h3>Право</h3><p>Бакалаврський, магістерський і третій освітньо-науковий рівні.</p><i>↓</i></Link><Link href="/programs/public-administration"><span>02</span><b>D4</b><h3>Публічне управління та адміністрування</h3><p>Бакалаврські, магістерські та освітньо-наукові траєкторії.</p><i>→</i></Link><Link href="/research/postgraduate-doctoral#phd"><span>03</span><b>PhD</b><h3>Аспірантура</h3><p>Програми, вступ, вартість, документи та контакти.</p><i>→</i></Link><Link href="/admissions"><span>04</span><b>2026</b><h3>Вступ на програми факультету</h3><p>Строки, випробування, результати та консультація.</p><i>→</i></Link></div><div className="faculty-link-grid" id="law-levels"><Link className="faculty-link-card faculty-link-card-blue" href="/programs/law#education-levels"><span>01 / Перший рівень</span><h3>Бакалавр D8 «Право»</h3><p>Навчальний план, обов’язкові й вибіркові компоненти, практика та атестація.</p><b>Відкрити рівень →</b></Link><Link className="faculty-link-card faculty-link-card-gold" href="/programs/law#education-levels"><span>02 / Другий рівень</span><h3>Магістр D8 «Право»</h3><p>Поглиблена професійна підготовка, дослідження та кваліфікаційна робота.</p><b>Відкрити рівень →</b></Link><Link className="faculty-link-card" href="/research/postgraduate-doctoral#phd"><span>03 / Третій рівень</span><h3>PhD «Право»</h3><p>Освітньо-наукова програма, вступ, дослідницька траєкторія та документи.</p><b>Відкрити рівень →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-repository" id="faculty-discussion"><div className="wrap"><div className="sec-head"><div><div className="idx">13 / Громадське обговорення освітніх програм</div><h2>Проєкти, пропозиції та результати розгляду</h2></div><p>Обговорення не об’єднане з репозитарієм і має власний розділ.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card" href="/programs/law#quality"><span>01 / D8 «Право»</span><h3>Обговорення освітньої програми</h3><p>Проєкти програм, супровідні документи, пропозиції стейкголдерів, рішення та затверджені редакції.</p><b>До обговорення →</b></Link><Link className="faculty-link-card" href="/programs/public-administration#quality"><span>02 / D4</span><h3>Публічне управління та адміністрування</h3><p>Матеріали консультацій, отримані пропозиції та результати їх розгляду.</p><b>До обговорення →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-repository" id="faculty-repository"><div className="wrap"><div className="sec-head"><div><div className="idx">14 / Репозитарій</div><h2>Кваліфікаційні роботи факультету</h2></div><p>Роботи можна фільтрувати за програмою, роком, автором і науковим керівником.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-dark" href="/research/theses"><span>01 / D8 «Право»</span><h3>Бакалаврські й магістерські роботи</h3><p>Пошук за автором, роком, програмою та науковим керівником.</p><b>Відкрити каталог →</b></Link><Link className="faculty-link-card faculty-link-card-blue" href="/research/theses"><span>02 / D4</span><h3>Публічне управління та адміністрування</h3><p>Дослідження з публічної політики, врядування, управління та розвитку громад.</p><b>Відкрити каталог →</b></Link></div></div></section>

      <div id="faculty-quality"><EducationQualitySection entries={departmentEntries} pagePath="/departments/law-faculty" index="15" description="Результати моніторингу якості освіти, обговорення змін до освітніх програм, щорічне оцінювання науково-педагогічних працівників і документи факультету." /><PageDocuments pagePath="/departments/law-faculty" /></div>

      <div id="department-news"><AcademicNews slugs={["law", "public-administration"]} title="Новини юридичного факультету" /><DepartmentEditorialContent entries={departmentEntries.filter((entry) => !["hero", "teacher", "partner"].includes(entry.entryType))} /></div>
    </SectionHub>
    <SiteFooter />
  </main>;
}
