import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";
import { LawFacultyTeam } from "../../components/LawFacultyTeam";
import { PageDocuments } from "../../components/PageDocuments";
import { DepartmentEditorialContent } from "../../components/DepartmentEditorialContent";
import { getDepartmentEntries } from "@/lib/department-content";
import { SectionHub, type SectionHubItem } from "../../components/SectionHub";
import { EducationQualitySection } from "../../components/EducationQualitySection";
import { AcademicNews } from "../../components/AcademicNews";
import { AcademicProfileCard } from "../../components/AcademicProfileCard";

export const metadata: Metadata = {
  title: "Юридичний факультет",
  description: "Структура юридичного факультету АПСВТ: керівництво, кафедри, освітні програми, практика, наука, документи та студентські ініціативи.",
};

const departments = [
  ["01", "Кафедра конституційного, адміністративного та фінансового права", "Конституційне, адміністративне, фінансове й муніципальне право.", "/programs/law#department"],
  ["02", "Кафедра публічного управління та адміністрування", "Публічна політика, служба, розвиток громад і соціальний діалог.", "/programs/public-administration#department"],
  ["03", "Кафедра цивільного, трудового та господарського права", "Цивільне, господарське, трудове право та судовий захист.", "/departments/private-law"],
  ["04", "Кафедра кримінального права, процесу та криміналістики", "Кримінальне право, процес, захист прав людини та криміналістика.", "/departments/criminal-law"],
] as const;

const facultySections: readonly SectionHubItem[] = [
  { id: "faculty-about", index: "01", title: "Про факультет", description: "Історія, місія, пріоритети та структура.", icon: "F", aliases: ["faculty-history", "faculty-mission", "faculty-structure"] },
  { id: "faculty-leadership", index: "02", title: "Керівництво й деканат", description: "Декан, заступники, деканат і документи.", icon: "DEC", aliases: ["faculty-dean", "faculty-dean-office"] },
  { id: "departments", index: "03", title: "Кафедри", description: "Чотири академічні підрозділи факультету.", icon: "4" },
  { id: "faculty-practice-centres", index: "04", title: "Клініка й лабораторія", description: "«Феміда» та навчальна лабораторія криміналістики.", icon: "LAB" },
  { id: "faculty-practice-bases", index: "05", title: "Бази практики", description: "Професійні установи та практична підготовка.", icon: "PR" },
  { id: "faculty-science", index: "06", title: "Наука й гуртки", description: "Студентські дослідження та школа муніципального права.", icon: "SCI", aliases: ["municipal-law-school"] },
  { id: "faculty-governance", index: "07", title: "Управління факультетом", description: "Вчена рада та студентське самоврядування.", icon: "GOV", aliases: ["faculty-council", "faculty-student-government"] },
  { id: "law-teachers", index: "08", title: "Колектив факультету", description: "Керівництво, викладачі, науковці та практики.", icon: "TEAM" },
  { id: "faculty-programmes", index: "09", title: "Освітні програми", description: "D8 «Право», D4 «Публічне управління» та PhD.", icon: "OP" },
  { id: "faculty-repository", index: "10", title: "Репозитарій і обговорення", description: "Кваліфікаційні роботи та публічні консультації.", icon: "REP" },
  { id: "faculty-quality", index: "11", title: "Якість і документи", description: "Моніторинг, оцінювання, рішення та офіційні файли.", icon: "✓" },
  { id: "department-news", index: "12", title: "Новини факультету", description: "Події, публікації та матеріали кафедр.", icon: "NEWS" },
];

const practiceCategories = ["Суди", "Органи прокуратури", "Органи Національної поліції", "Адвокатура", "Органи державної влади", "Місцеве самоврядування", "Юридичні компанії", "Підприємства й організації"];

export default async function Page() {
  const departmentEntries = await getDepartmentEntries("/departments/law-faculty");

  return <main id="top"><SiteHeader />
    <section className="law-faculty-hero"><div className="law-faculty-hero-image"><Image src="https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1800&q=92&auto=format&fit=crop" alt="Правнича освіта" fill sizes="(max-width: 720px) 100vw, 56vw" priority /></div><div className="wrap law-faculty-hero-copy"><Link href="/departments">← Усі факультети й кафедри</Link><span>ЮФ · з 1994 року</span><h1>Юридичний<br /><em>факультет</em></h1><p>Фундаментальна правнича освіта, клінічна практика, криміналістична лабораторія та дослідження, що працюють для людини й держави.</p><div><b>4</b><span>кафедри</span><b>2</b><span>практичні осередки</span></div></div></section><div className="hero-rule" />

    <SectionHub sections={facultySections} eyebrow="Структура юридичного факультету" description="Оберіть потрібний напрям. Відкриється тільки один розділ, а вкладені картки приведуть до конкретної кафедри, програми, документа або матеріалу.">

      <section className="law-faculty-intro" id="faculty-about"><div className="wrap law-faculty-intro-grid"><div><div className="idx">01 / Про факультет</div><h2>Від першого набору до правничої екосистеми</h2></div><div><p className="program-lede">Становлення факультету розпочалося з першого набору студентів у 1994 році. Сьогодні він готує практиків для судових, правозахисних і правоохоронних установ, органів влади, місцевого самоврядування та юридичного бізнесу.</p><p>До викладання залучені науковці та юристи-практики. Виїзні заняття, гостьові лекції, клінічна робота й лабораторні симуляції перетворюють теорію на професійну дію.</p><nav className="faculty-subsection-nav" aria-label="Про факультет: підрозділи"><a href="#faculty-about"><b>Загальна інформація</b><span>01</span></a><a href="#faculty-history" id="faculty-history"><b>Історія факультету</b><span>02</span></a><a href="#faculty-mission" id="faculty-mission"><b>Місія та стратегічні пріоритети</b><span>03</span></a><a href="#faculty-structure" id="faculty-structure"><b>Структура факультету</b><span>04</span></a></nav><div className="law-faculty-milestones"><span><b>1994</b>перший набір студентів</span><span><b>2014</b>відкриття клініки «Феміда»</span><span><b>3</b>рівні вищої освіти</span></div></div></div></section>

      <section className="faculty-structure-section faculty-leadership" id="faculty-leadership"><div className="wrap"><div className="sec-head"><div><div className="idx">02 / Керівництво та деканат</div><h2>Команда, що координує факультет</h2></div><p>Профілі керівництва, функції деканату та офіційні матеріали зібрано в одному розділі.</p></div><div className="faculty-leadership-grid" id="faculty-dean"><AcademicProfileCard badge="Декан факультету" person={{ name: "Ярослав Журавель", role: "доктор юридичних наук, професор, декан юридичного факультету", summary: "Координує освітню, наукову й організаційну роботу факультету. Досліджує муніципальне право, децентралізацію та місцеве самоврядування.", image: "/people/law/yaroslav-zhuravel.webp", tags: ["муніципальне право", "децентралізація", "управління факультетом"], links: [{ label: "ORCID", href: "https://orcid.org/0000-0002-7623-9144" }, { label: "Google Scholar", href: "https://scholar.google.com/citations?user=d_ca1TwAAAAJ&hl=uk" }] }} /><AcademicProfileCard badge="Заступниця декана" person={{ name: "Світлана Шевченко", role: "старша викладачка, заступниця декана з виховної роботи", summary: "Працює в Академії з 1995 року. Супроводжує виховну й комунікаційну роботу факультету та викладає юридичну деонтологію і професійну етику.", image: "/people/law/svitlana-shevchenko.webp", tags: ["виховна робота", "юридична деонтологія", "професійна комунікація"], links: [{ label: "ORCID", href: "https://orcid.org/0000-0001-5932-7487" }] }} /><aside className="faculty-office-card" id="faculty-dean-office"><span>Деканат</span><h3>Організаційна підтримка студентів і викладачів</h3><ul><li>організація освітнього процесу;</li><li>комунікація з кафедрами;</li><li>практична підготовка;</li><li>студентські звернення;</li><li>документообіг факультету.</li></ul><Link href="/contacts">Контакти Академії →</Link></aside></div></div></section>

      <section className="law-faculty-departments" id="departments"><div className="wrap"><div className="sec-head"><div><div className="idx">03 / Академічна структура</div><h2>Чотири кафедри — єдина траєкторія</h2></div><p>Кожна картка відкриває сторінку кафедри з командою, освітньою та науковою діяльністю, матеріалами й контактами.</p></div><div className="law-department-grid">{departments.map(([number, title, text, href]) => <Link href={href} key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p><b>Відкрити кафедру →</b></Link>)}</div></div></section>

      <section className="law-practice-showcase" id="faculty-practice-centres"><div className="wrap"><div className="law-practice-head"><div><div className="idx">04 / Навчально-практичні підрозділи</div><h2>Професійні дії ще під час навчання</h2></div><p>Кожен осередок має окрему сторінку з описом роботи, командою, навчальною діяльністю, новинами, документами й контактами.</p></div><div className="law-practice-grid law-practice-grid-two"><Link href="/programs/law/legal-clinic"><span>01</span><small>Правнича допомога</small><h3>Юридична клініка «Феміда»</h3><p>Інтерв’ювання клієнта, правовий аналіз, підготовка відповіді, правопросвітницькі заходи й супервізія викладача.</p><b>Відкрити сторінку клініки →</b></Link><Link href="/programs/law/forensic-laboratory"><span>02</span><small>Навчальна лабораторія</small><h3>Лабораторія криміналістики</h3><p>Матеріально-технічне забезпечення, фіксація слідів, моделювання процесуальних дій, практична й наукова робота.</p><b>Відкрити сторінку лабораторії →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-practice-bases" id="faculty-practice-bases"><div className="wrap"><div className="sec-head"><div><div className="idx">05 / Бази практики</div><h2>Професійне середовище факультету</h2></div><p>Конкретну базу та строк практики факультет підтверджує для відповідного навчального року, договору й індивідуальної траєкторії студента.</p></div><div className="faculty-category-grid">{practiceCategories.map((category, index) => <Link href="/programs/law#department" key={category}><span>{String(index + 1).padStart(2, "0")}</span><b>{category}</b><i>↗</i></Link>)}</div><div className="faculty-action-note"><p><b>Студентам</b> Інформація про направлення, керівника та звітність з практики надається кафедрою.</p><Link href="/contacts">Уточнити контакти →</Link></div></div></section>

      <section className="faculty-structure-section faculty-science-directory" id="faculty-science"><div className="wrap"><div className="sec-head"><div><div className="idx">06 / Наукова діяльність</div><h2>Від студентського гуртка до наукової школи</h2></div><p>Дослідницькі напрями, публікації, конференції та проєкти пов’язані з освітніми програмами факультету.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-blue" href="/research"><span>01 / Студентська наука</span><h3>Історико-правовий гурток «Фенікс»</h3><p>Зустрічі, дослідницькі напрями, плани роботи та студентські наукові проєкти.</p><b>Наука в Академії →</b></Link><Link className="faculty-link-card faculty-link-card-gold" href="/news/best-municipal-law-research-2025" id="municipal-law-school"><span>02 / Наукова школа</span><h3>Школа муніципального права</h3><p>Історія школи, учасники, дослідження місцевого самоврядування, публікації та конкурсні роботи.</p><b>Відкрити матеріал →</b></Link><Link className="faculty-link-card" href="/research/conferences"><span>03 / Події</span><h3>Конференції та наукові заходи</h3><p>Календар дискусій, круглих столів, конференцій і презентацій результатів.</p><b>Перейти до конференцій →</b></Link><Link className="faculty-link-card" href="/research/journals"><span>04 / Публікації</span><h3>Наукові видання й репозитарій</h3><p>Журнали, збірники, монографії та відкриті студентські дослідження.</p><b>Перейти до видань →</b></Link></div></div></section>

      <section className="faculty-structure-section faculty-governance" id="faculty-governance"><div className="wrap"><div className="sec-head"><div><div className="idx">07 / Управління факультетом</div><h2>Колегіальні та студентські рішення</h2></div><p>Два окремі напрями для академічного врядування та участі студентів у житті факультету.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-dark" href="/documents#governance" id="faculty-council"><span>01 / Вчена рада</span><h3>Вчена рада юридичного факультету</h3><p>Склад, положення, план роботи, засідання, рішення, протоколи та архів за роками.</p><b>Перейти до документів →</b></Link><Link className="faculty-link-card faculty-link-card-gold" href="/students/council" id="faculty-student-government"><span>02 / Студенти</span><h3>Студентське самоврядування</h3><p>Склад ради, проєкти, ініціативи, новини, події та контакти студентської команди.</p><b>Відкрити студентську раду →</b></Link></div></div></section>

      <div><LawFacultyTeam /><section className="faculty-team-directory"><div className="wrap"><div className="sec-head"><div><div className="idx">08 / Кафедральні команди</div><h2>Знайдіть викладача за підрозділом</h2></div><p>Повні й актуальні профілі фахівців інших кафедр відкриваються на їхніх сторінках.</p></div><div className="faculty-category-grid">{departments.map(([number, title, , href]) => <Link href={href} key={number}><span>{number}</span><b>{title.replace("Кафедра ", "")}</b><i>↗</i></Link>)}</div></div></section></div>

      <section className="faculty-programmes" id="faculty-programmes"><div className="wrap"><div className="sec-head"><div><div className="idx">09 / Освітні програми</div><h2>Освітні траєкторії факультету</h2></div><p>На сторінці програми доступні опис, навчальний план, освітні компоненти, силабуси, вибіркові дисципліни, практика, атестація, акредитація та документи.</p></div><div className="faculty-programme-grid"><Link href="/programs/law"><span>01</span><b>D8</b><h3>Право</h3><p>Бакалаврський, магістерський і третій освітньо-науковий рівні.</p><i>→</i></Link><Link href="/programs/public-administration"><span>02</span><b>D4</b><h3>Публічне управління та адміністрування</h3><p>Бакалаврські, магістерські та освітньо-наукові траєкторії.</p><i>→</i></Link><Link href="/research/postgraduate-doctoral#phd"><span>03</span><b>PhD</b><h3>Аспірантура</h3><p>Програми, вступ, вартість, документи та контакти.</p><i>→</i></Link><Link href="/admissions"><span>04</span><b>2026</b><h3>Вступ на програми факультету</h3><p>Строки, випробування, результати та консультація.</p><i>→</i></Link></div></div></section>

      <section className="faculty-structure-section faculty-repository" id="faculty-repository"><div className="wrap"><div className="sec-head"><div><div className="idx">10 / Відкриті матеріали</div><h2>Репозитарій і публічне обговорення</h2></div><p>Кваліфікаційні роботи можна фільтрувати за програмою, роком і керівником; пропозиції до освітніх програм оприлюднюються разом із результатами розгляду.</p></div><div className="faculty-link-grid"><Link className="faculty-link-card faculty-link-card-dark" href="/research/theses"><span>01 / Репозитарій</span><h3>Кваліфікаційні роботи D8 «Право»</h3><p>Бакалаврські й магістерські роботи з пошуком за автором, роком, програмою та науковим керівником.</p><b>Відкрити каталог →</b></Link><Link className="faculty-link-card faculty-link-card-blue" href="/research/theses"><span>02 / Репозитарій</span><h3>Кваліфікаційні роботи D4 «Публічне управління»</h3><p>Дослідження з публічної політики, врядування, управління та розвитку громад.</p><b>Відкрити каталог →</b></Link><Link className="faculty-link-card" href="/programs/law#quality"><span>03 / Обговорення ОП</span><h3>D8 «Право»</h3><p>Проєкти програм, супровідні документи, пропозиції стейкголдерів, рішення та затверджені редакції.</p><b>До обговорення →</b></Link><Link className="faculty-link-card" href="/programs/public-administration#quality"><span>04 / Обговорення ОП</span><h3>D4 «Публічне управління»</h3><p>Матеріали консультацій, отримані пропозиції та результати їх розгляду.</p><b>До обговорення →</b></Link></div></div></section>

      <div id="faculty-quality"><EducationQualitySection entries={departmentEntries} pagePath="/departments/law-faculty" index="11" description="Результати моніторингу якості освіти, обговорення змін до освітніх програм, щорічне оцінювання науково-педагогічних працівників і документи факультету." /><PageDocuments pagePath="/departments/law-faculty" /></div>

      <div id="department-news"><AcademicNews slugs={["law", "public-administration"]} title="Новини юридичного факультету" /><DepartmentEditorialContent entries={departmentEntries.filter((entry) => !["hero", "teacher", "partner"].includes(entry.entryType))} /></div>
    </SectionHub>
    <SiteFooter />
  </main>;
}
